### ISSUE TITLE
undefined error?

### ISSUE THREAD

**Issue by SoulDemon** [maierfelix/POGOserver#10]
https://gyazo.com/15cd2d38d7ab67076adc5ac49567f77a

**Comment by maierfelix** [comment]
This should be a related to the ``pogobuf`` package or ``pogo-asset-downloader``.
Check the ``SERVER_POGO_CLIENT_USERNAME`` and ``SERVER_POGO_CLIENT_PASSWORD`` in the config.

**Comment by SoulDemon** [comment]
Yup, Put my own PTC account in there already... https://gyazo.com/3b0b8d41e6ff77117cd9105f03ac92d6

**Comment by maierfelix** [comment]
Fixed in https://github.com/maierfelix/POGOserver/commit/b92bd36ce031baf593947f2bf7b5687cf57530b9
Edit [this](https://github.com/maierfelix/POGOserver/blob/master/cfg.js#L36) line to define your provider

**Comment by SoulDemon** [comment]
Now its just stuck on booting server.

**Comment by maierfelix** [comment]
Fixed https://github.com/maierfelix/POGOserver/commit/dcd61f937d64c471d6de9011fe48b9442772eca6
