### ISSUE TITLE
Error when I launch "install-windows" or "run-windows".

### ISSUE THREAD

**Issue by AxelReshiram** [maierfelix/POGOserver#100]
Hello ! I have a Probleme when I launch "install-windows" or "run-windows".
I'm using Node.js version 6.5.0
I've got this :

(node:3232) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> node-protobuf@1.3.3 install C:\Users\AxelReshiram\Desktop\POGOserver-master\node_modules\node-protobuf
> node-gyp rebuild

C:\Users\AxelReshiram\Desktop\POGOserver-master\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
G▒n▒ration des projets individuellement dans cette solution. Pour activer la g▒n▒ration en parall▒le, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\AxelReshiram\Desktop\POGOserver-master\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AxelReshiram\Desktop\POGOserver-master\node_modules\node-protobuf
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\AxelReshiram\Desktop\POGOserver-master\npm-debug.log

> POGOServer@0.5.0 start C:\Users\AxelReshiram\Desktop\POGOserver-master
> npm run babel-node -- ./src/index.js

And the window closes

**Comment by srg84** [comment]
**The Windows SDK version 8.1 was not found**

maybe you have to install it

**Comment by AxelReshiram** [comment]
Thanks for your quick response :) I try this :+1:

**Comment by AxelReshiram** [comment]
Not work :/

**Comment by maselogico** [comment]
I had problems installing on windows 7 my computer since I installed several frameworks, windows updates, microsoft visual studios c ++ many. The correct and do a fresh install of Windows and install the necessary requirements that will work. It worked for me and today I have a virtual machine running and a vps.

**Comment by MZorzy** [comment]
can't run with run-linux.sh too.
they not install all necessary module.

**Comment by AxelReshiram** [comment]
All I need to have is a Virtual Machine with Windows ?

**Comment by srg84** [comment]
Read the error it's the same?

The Windows SDK version 8.1 was not found

**Comment by MZorzy** [comment]
there are a lot of errors, not only one of sdk-

**Comment by AxelReshiram** [comment]
Other solutions?
