### ISSUE TITLE
New Discord

### ISSUE THREAD

**Issue by HusbandoMax** [maierfelix/POGOserver#106]
Why was discord deleted? Will there be a new group?
Edit:
We've created a new discord at least until we hear what happened to the last one so everyone can come chat, help each other or anything really.

**Comment by loveboyita** [comment]
:/

**Comment by HusbandoMax** [comment]
Maybe till we hear something about it we can use a temp one just so people that need help can get it?

**Comment by maierfelix** [comment]
Discord links arent allowed here
