### ISSUE TITLE
game_master error

### ISSUE THREAD

**Issue by DeadlyMelqn** [maierfelix/POGOserver#107]
where can we locate the files for this.

**Comment by icdance** [comment]
You have to put correct information in cfg.js to download the assets and game master in the first time you run.

**Comment by DeadlyMelqn** [comment]
I have followed the guide and put my information in shouldn't it have not
downloaded it.

**Comment by DeadlyMelqn** [comment]
Ooooooh nvm the issue is that my account was banned I will retry this again
with an alternative google account,
