### ISSUE TITLE
No response, no errors

### ISSUE THREAD

**Issue by KeJunMao** [maierfelix/POGOserver#11]
![](https://kejun.tk/data/xxxx.png)

**Comment by maierfelix** [comment]
Try to run ``npm run start``, either with or without ``sudo``.
Make sure you have nodejs >= 6 installed.

**Comment by KeJunMao** [comment]
@maierfelix 

img:

![](https://kejun.tk/data/sososo.png)

**Comment by KeJunMao** [comment]
update Nodejs
