### ISSUE TITLE
any help with this error running windows 7 sp1

### ISSUE THREAD

**Issue by qnzboi102** [maierfelix/POGOserver#110]
425 error Windows_NT 6.1.7601
426 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
427 error node v6.5.0
428 error npm  v3.10.3
429 error code ELIFECYCLE
430 error node-protobuf@1.3.3 install: `node-gyp rebuild`
430 error Exit status 1
431 error Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
431 error Make sure you have the latest version of node.js and npm installed.
431 error If you do, this is most likely a problem with the node-protobuf package,
431 error not with npm itself.
431 error Tell the author that this fails on your system:
431 error     node-gyp rebuild
431 error You can get information on how to open an issue for this project with:
431 error     npm bugs node-protobuf
431 error Or if that isn't available, you can get their info via:
431 error     npm owner ls node-protobuf
431 error There is likely additional logging output above.
432 verbose exit [ 1, true ]

**Comment by maierfelix** [comment]
Answered multiple times here
