### ISSUE TITLE
Info on how to set it up

### ISSUE THREAD

**Issue by RikudouSage** [maierfelix/POGOserver#111]
Is there some info on how to set the server up? I have it running but I don't know how to add users to server, how to add pokemon spawns etc. Any help would be appreciated.

**Comment by DracoMilesX** [comment]
In the README their is a section Tunneling setup. Your friends need to do this as well. Except you need to port forwarding on your router and give your home ip to your friends as well.

**Comment by MZorzy** [comment]
+ on docker file there are some informations

**Comment by RikudouSage** [comment]
I know how to set up the server on its own, it's pretty easy, I just don't know how to register account for use in game, how to add spawns etc.

**Comment by DracoMilesX** [comment]
You can register a account like the normal way you do with Pokemon Go and that is connect a google account to it.

I am not certain but random spawns aren't included yet? And gyms/pokestops being worked on

**Comment by RikudouSage** [comment]
So it's possible to login only via Google? Also in screenshot on homepage there is some screenshot of some kind of app where he adds a pokestop/gym, where can I find it?

**Comment by DracoMilesX** [comment]
It's possible only with google at this moment.

The app is the api branch you can download the zip for it and then extract and place it in the root of your webfolder.

**Comment by RikudouSage** [comment]
Thanks a lot, will ask later if I find anything confusing :)

Wouldn't it be better to include all this info in the wiki?

**Comment by RikudouSage** [comment]
Another problem... how to set the CORS on the server? The API refuses to connect to server.

**Comment by MZorzy** [comment]
i have setupa ptc account, POGOserver download data from ni.ntic 
but can't test because my phone ,android rooted with xposed installed, connect to originale server. not my one

**Comment by DracoMilesX** [comment]
The wiki is still a work in progress first trying to finish the installation parts then I will add the rest.

I dunno about the CORS/API haven't managed to get a connection myself.
