### ISSUE TITLE
invalid provider ptc

### ISSUE THREAD

**Issue by MZorzy** [maierfelix/POGOserver#113]
i start the server that download all dumping model for android AND ios (why no one?)
if i go to ip:port from browser phone (no wifi) i see on server 
"Unknown request url: https://82.106.80.141:3000/" so all is running correct

 BUT i set PTC account on cfg.js (accound working cause DL)
on server :
[Console] GET_PLAYER
[Console] CHECK_CHALLENGE
[Console] Invalid provider! Kicking..

? it connect to nina.ic server but not valid from phone to server?

**Comment by maierfelix** [comment]
PTC accounts ingame arent supported yet

**Comment by MZorzy** [comment]
it's a login problem phone-pogoserver or pogoserver-nian.ic servers ?
possibile remove login test ?

with ptc account download all model also
```
[Console] Dumping model pm0150..
[Console] Dumping model pm0151..
[Console] Dumped 151 iOS assets successfully!
[Console] Dumped all assets successfully!
[Console] Downloaded assets are valid! Proceeding..
```
