### ISSUE TITLE
[Console] StopError: Status code 403 received from HTTPS request

### ISSUE THREAD

**Issue by Nheters** [maierfelix/POGOserver#114]
I have this issue, and i dont know how to fix  #it
            ______ _____ _____ _____
            | ___ \  _  |  __ \  _  |
            | |_/ / | | | |  \/ | | | ___  ___ _ ____   _____ _ __
            |  __/| | | | | __| | | |/ __|/ _ \ '__\ \ / / _ \ '__|
            | |   \ \_/ / |_\ \ \_/ /\__ \  __/ |   \ V /  __/ |
            \_|    \___/ \____/\___/ |___/\___|_|    \_/ \___|_|

[Console] Booting Server v0.5.0
[Console] Required assets are missing! Preparing dump session..
[Console] StopError: Status code 403 received from HTTPS request

**Comment by MZorzy** [comment]
if u have pokeomoexposed module not check ssl tab

**Comment by ranrinc** [comment]
I encounter the same problem. Anyone know why 403? Should I disable https? or is there a files need to be installed on Apache?

**Comment by Nheters** [comment]
when i start the server that error shows, and yes im using exposed, but im not even using it right now, is at the moment that i try to run the server

**Comment by ranrinc** [comment]
This is what appearing on my terminal. Need help! its close but server NO GO...

<img width="572" alt="screen shot 2016-09-01 at 11 27 01 pm" src="https://cloud.githubusercontent.com/assets/15801696/18175498/afd05068-709b-11e6-8040-3db5756b76fe.png">

**Comment by ruchern** [comment]
@ranrinc Are you running it on a cloud server like DigitalOcean/AWS? The IP ranges were banned by Niantic and you are unable to download the assets from the actual server.

**Comment by ranrinc** [comment]
@ruchern, yes you are totally right. I forget about IP banned. Any idea on how to overcome this obstacle? I do have IP available to be used. Anyway thanks for the info.

**Comment by ruchern** [comment]
@ranrinc Not possible unless you run a proxy on your hosting back to your own host machine or some sort.

**Comment by Retalyx** [comment]
ruchern is right, my dedicated server IP is banned, so i had to use a proxy to download required assets from Niantic servers.
So if you have a banned IP, use a prxy or change your IP
