### ISSUE TITLE
Unknown request: LEVEL_UP_REWARDS

### ISSUE THREAD

**Issue by MZorzy** [maierfelix/POGOserver#116]
`[Console] #####
[Console] LEVEL_UP_REWARDS
[Console] CHECK_CHALLENGE
[Console] GET_HATCHED_EGGS
[Console] GET_INVENTORY
[Console] CHECK_AWARDED_BADGES
[Console] DOWNLOAD_SETTINGS
[Console] Unknown request: LEVEL_UP_REWARDS
`

**Comment by RoccoDeveloping** [comment]
Which commit are you using?

**Comment by MZorzy** [comment]
Last master

**Comment by RoccoDeveloping** [comment]
Go to Releases > download the last release
