### ISSUE TITLE
Asset Digests - HELP QUICK - player.asset_digests is null

### ISSUE THREAD

**Issue by RoccoDeveloping** [maierfelix/POGOserver#117]
In the last RELEASE the player.asset_digests is null. So whenever a player joins it says:

Got request: GET_ASSET_DIGEST
Got request: CHECK_CHALLENGE
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
[Console] Response error: TypeError: Cannot read property 'buffer' of null

I am 100% sure that AssetDigests is causing the problem.

**Comment by MZorzy** [comment]
1st upgrade to last master then open issue.

**Comment by RoccoDeveloping** [comment]
In last master all commands are broken. You can't spawn Pokémon, so it's useless.

**Comment by MZorzy** [comment]
what's last working commit ?

**Comment by vodkislov** [comment]
Download the release. The master is still unstable
