### ISSUE TITLE
Stuck at middle of loading bar

### ISSUE THREAD

**Issue by UltiNaruto** [maierfelix/POGOserver#120]
![image](https://cloud.githubusercontent.com/assets/14176397/18178186/ab050506-707d-11e6-8211-f7a38c0c3d51.png)

This is what the server spams when I'm stuck at loading bar. On 0.4.9 it was working just fine.

**Comment by AlexTheCoder007** [comment]
me too help pls

**Comment by ruchern** [comment]
Same problem here.

**Comment by marcomarotta** [comment]
same problem. using latest commit (978c14c)
