### ISSUE TITLE
Failed npm run babel-node

### ISSUE THREAD

**Issue by TheBob123** [maierfelix/POGOserver#121]
When I try to start the server it fails at npm run babel-node

OS: Windows 10 64bit
Nodejs version: 6.5.0

[npm-debug.txt](https://github.com/maierfelix/POGOserver/files/450383/npm-debug.txt)

**Comment by RecklessIt** [comment]
I'm having the same problem on Linux Mint with Nodejs 6.5.0.

**Comment by ranrinc** [comment]
Now make sure you guys install protobuf <- the hardest part to install. I still fail to complete this procedure especially for Windows.

**Comment by RandomGamer055** [comment]
why do you need protobuf

**Comment by ranrinc** [comment]
@RandomGamer055 that question need to be asked to the developer. However you will require protobuf else the server wont run and yes for Windows will be the hardest part. I'm trying to install protobuf myself and if I'm successful will update the WIKI pages.

**Comment by cliffsmits007** [comment]
@TheBob123  Try to download the presetup for version 5.8 its included protobuf.
you only need to run the trainer-bat and emptry youré database for a fresh install.

https://mega.nz/#!iwNDkBAL!3kqkp2daseDNHfSYp_4I349UIgp8Q51Mp0PjDCdzM8g

**Comment by Cronick** [comment]
@cliffsmits007 It's not allowed to link to pre-compiled server packages.
Only download links to node_modules is allowed
