### ISSUE TITLE
Unexpected token G in JSON at position 1

### ISSUE THREAD

**Issue by Sillyblower** [maierfelix/POGOserver#126]
First of all... nice work @maierfelix  !!!
Now the problem, every time a start the server i got this error and i don´t now where to look. 
I use the Pogoserver-master 5.0 everything works fine if i follow your updates but this one idk.

> SyntaxError: Unexpected token G in JSON at position 1

[Console] Success: DOWNLOAD_ITEM_TEMPLATES => 152740
[Console] Success: CHECK_CHALLENGE => 3
[Console] Success: GET_HATCHED_EGGS => 2
[Console] Success: GET_INVENTORY => 29
[Console] Success: CHECK_AWARDED_BADGES => 2
[Console] Success: DOWNLOAD_SETTINGS => 187
[Console] #####
[Console] GET_MAP_OBJECTS
[Console] CHECK_CHALLENGE
[Console] GET_HATCHED_EGGS
[Console] GET_INVENTORY
[Console] CHECK_AWARDED_BADGES
[Console] DOWNLOAD_SETTINGS
**[Console] SyntaxError: Unexpected token G in JSON at position 1**
[Console] Success: GET_MAP_OBJECTS => 504
[Console] Success: CHECK_CHALLENGE => 3

**Comment by Sillyblower** [comment]
![error](https://cloud.githubusercontent.com/assets/21693288/18182521/9ba32cce-7090-11e6-9856-390222d5367d.png)

**Comment by AlexTheCoder007** [comment]
me too

**Comment by Cronick** [comment]
Is this still a problem @Sillyblower?

**Comment by maierfelix** [comment]
Likely caused by an empty or invalid database field, make sure you clear your database before upgrading, so all tables get generated correctly
