### ISSUE TITLE
Cant connect?

### ISSUE THREAD

**Issue by AsteroidC** [maierfelix/POGOserver#127]
So i did everything right but when i connect i just get in the normal niantic servers.. Pls help me :)

**Comment by MZorzy** [comment]
not all so right :-D
which device, how u modded it ?

**Comment by AsteroidC** [comment]
Umm im bad with these things, but i put my ptc or googel account there.. nothing else really.. Just added some stardust for catching pokemon and stuff.. I watched a video on youtube..

**Comment by AsteroidC** [comment]
Ok so i watched this video from Kuzner and did all what he did on the video. Im using honor 6 0.35.0 version. I put endpoint to what the console says "Server running at..."

**Comment by AsteroidC** [comment]
Ok you can close this.. Im not connected to wifi bcause wifi doesnt work on honor 6 -.-
