### ISSUE TITLE
Crash running server command

### ISSUE THREAD

**Issue by ranrinc** [maierfelix/POGOserver#130]
I got this crash on all command call.
 
for example '/save' and '/spawn unknown mewtwo 10'

I include the picture
![screen shot 2016-09-02 at 3 23 46 pm](https://cloud.githubusercontent.com/assets/15801696/18197468/84749b14-7121-11e6-860d-9688da27d0cd.png)

anyone know how to help?

**Comment by RoccoDeveloping** [comment]
If you want it to work, download the latest release from the Releases tab. A recode is in progress in the last commits

**Comment by ranrinc** [comment]
@RoccoDeveloping I download the latest master, so its not yet completed?

**Comment by RoccoDeveloping** [comment]
Nope. Not yet.

**Comment by RoccoDeveloping** [comment]
However, I still suggest you to upgrade to the latest master, as it contains less bugs. Just wait.
