### ISSUE TITLE
Crash running server comands in new version and cant spawn pokemon in 0.4.9

### ISSUE THREAD

**Issue by CapitGame** [maierfelix/POGOserver#133]
Please help

**Comment by RoccoDeveloping** [comment]
Post the error message.

**Comment by andi1up** [comment]
Not OP but I'm having the same problem. The error I get for every command is...

**Comment by Retalyx** [comment]
i saw that the function spawnPkmnAtPlayer was in src/players.js , but this file doesn't exist anymore https://github.com/maierfelix/POGOserver/blob/1cc01c2b3ce5da589a9ac9ed2fabc42f63401425/src/player.js#L316

**Comment by RoccoDeveloping** [comment]
Download the latest master

**Comment by maierfelix** [comment]
Spawning pkmn works but the spawn console command isnt implemented yet since much things are in recode state
