### ISSUE TITLE
Stuck on big "POGOserver" on startup

### ISSUE THREAD

**Issue by Retalyx** [maierfelix/POGOserver#142]
Hello, i can't start the server on Ubuntu 16.04 with latest commited version
When i run ./run-linux.sh the server show the bit "POGOserver" text and then, nothing happens... Any idea?

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN POGOServer@0.5.0 license should be a valid SPDX license expression

> POGOServer@0.5.0 start /home/retalyx/GitClones/POGOserver
> npm run babel-node -- ./src/index.js


> POGOServer@0.5.0 babel-node /home/retalyx/GitClones/POGOserver
> babel-node --presets=es2015 "./src/index.js"

            ______ _____ _____ _____
            | ___ \  _  |  __ \  _  |
            | |_/ / | | | |  \/ | | | ___  ___ _ ____   _____ _ __
            |  __/| | | | | __| | | |/ __|/ _ \ '__\ \ / / _ \ '__|
            | |   \ \_/ / |_\ \ \_/ /\__ \  __/ |   \ V /  __/ |
            \_|    \___/ \____/\___/ |___/\___|_|    \_/ \___|_|
```

**Comment by Retalyx** [comment]
Works with version 0.4.9

**Comment by maierfelix** [comment]
Does the same happen with a fresh clone and module installation of the latest commit?

**Comment by Retalyx** [comment]
Yes, this was from a fresh clone :/

**Comment by maierfelix** [comment]
Which commit?

**Comment by Retalyx** [comment]
i'm on the latest and the problem is still there : https://github.com/maierfelix/POGOserver/commit/978c14ce236f3ad22afff0ba496db09e0e22c11a

**Comment by maierfelix** [comment]
Did you copied over your old config file? Try copy the current one and refill all values

**Comment by Retalyx** [comment]
This worked :) Thanks
I'll check if i have the same problem as 4.9.0 https://github.com/maierfelix/POGOserver/issues/84

**Comment by Retalyx** [comment]
Everything is ok , thanks again, i close the issue :)
