### ISSUE TITLE
How Do I Install Protobuf?

### ISSUE THREAD

**Issue by Bearfear319** [maierfelix/POGOserver#143]
I have no idea how to install protobuf for it to load. or is it i just need a new "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" cuz the npm-cli.js is the problem for me.

**Comment by ranrinc** [comment]
ProtoBuf is the hardest part for Windows User to install. I'm installing it with ease on Linux and MacOS however with Windows its like hell because the guide is just not there.

**Comment by RandomGamer055** [comment]
im with you bearfear i have no clue how to get protobuf :(

**Comment by Cronick** [comment]
There is a guide in the wiki
https://github.com/maierfelix/POGOserver/wiki/Windows-Protobuf-How-To
