### ISSUE TITLE
SERVER CLOSES IN LOADIG 

### ISSUE THREAD

**Issue by NachoArtz** [maierfelix/POGOserver#144]
please help 
![ckuek](https://cloud.githubusercontent.com/assets/21962983/18221535/0f572dcc-7155-11e6-909b-9642110a4191.png)

**Comment by mianshoaib70** [comment]
Same problem here. Anyone help

**Comment by oosterlee** [comment]
I have that problem too.

**Comment by Sillyblower** [comment]
The command "npm install" will create that map node_modules.

**Comment by ranrinc** [comment]
Make sure protobuf install.. else you will get this problem.
