### ISSUE TITLE
Master is still unusable

### ISSUE THREAD

**Issue by ranrinc** [maierfelix/POGOserver#145]
Hi guys,

I believe the current status have not yet usable. Trying on MacOS which failed with several issue. As for uBuntu I got problem in some cases. So I guess we need to wait till we get a green light from the developer. Furthermore API pages is not accessible since its asking for root password which we dont know what is it.

**Comment by Sillyblower** [comment]
root password is written in the .save file.
Seriously ...

**Comment by Shipi1** [comment]
Yesterday the master branch is inusable, version 0.5 is in progress... Use 0.4.9 on release page, install nodejs, nms and protobuf module.

**Comment by RoccoDeveloping** [comment]
I also have problems with the release. Everything is a Type error (Cannot access property XXX of null/undefined)

**Comment by DracoMilesX** [comment]
Well the development of this project is still stated as experimental so of course it won't be usable yet fully.

Latest commits works for me except for the commands. (ubuntu)

**Comment by ZeBigDipper** [comment]
is there a way to install 0.4.9 on ubuntu?
