### ISSUE TITLE
How i add a pokestop and a Gym?

### ISSUE THREAD

**Issue by Shipi1** [maierfelix/POGOserver#146]
I downloaded Api branch and I do not know what to do

**Comment by RoccoDeveloping** [comment]
Upload it into an Apache webserver.
Then adjust the cfg.js to your needs.
Go to localhost, you can find the root password at <POGOSERVER DIR>/.save
Double clicka point on the map to add a Pokéstop/Gym.

**Comment by Sillyblower** [comment]
Don´t forget to insert your own api key for gmaps in the source (index.html)
X marks the spot :)

**Comment by Shipi1** [comment]
Says "unknown request url: https://127.0.0.1:3000/api"

**Comment by RoccoDeveloping** [comment]
You need to enable the API in the cfg.js

**Comment by cliffsmits007** [comment]
watch my guide how to setup API 

https://github.com/maierfelix/POGOserver/wiki/How-to-setup-API--services-through-Google-Console

when you want to add pokestops or gyms go to localhost and click on the live map below to add stops or gyms
