### ISSUE TITLE
Help (MySQL Error: ER_BAD_DB_ERROR: Unknown database 'pokémongo')

### ISSUE THREAD

**Issue by arozo** [maierfelix/POGOserver#148]
dose anyone know how to fix MySQL Error: ER_BAD_DB_ERROR: Unknown database 'pokémongo'

**Comment by DracoMilesX** [comment]
Connect with your database server and `CREATE DATABASE pokemongo;`

**Comment by arozo** [comment]
how do i do that?

**Comment by DracoMilesX** [comment]
Which OS are you running and which database tool?

**Comment by arozo** [comment]
im using windows and database tool?

**Comment by DracoMilesX** [comment]
Yeah are you running MySQL workbench or XAMPP or other tool?

**Comment by arozo** [comment]
xampp

**Comment by DracoMilesX** [comment]
Open XAMPP console panel, Press Admin at the mysql line then you should see this:
http://i.imgur.com/pPTAAQf.png

Click on New. Then fill in the database name under create new database and press create.

**Comment by arozo** [comment]
stie cant be reached?

**Comment by DracoMilesX** [comment]
Verify that apache is running.

**Comment by arozo** [comment]
oh ok that was off i will turn it on and check

**Comment by arozo** [comment]
ok i see that now

**Comment by arozo** [comment]
now what?

**Comment by DracoMilesX** [comment]
Press new on the left and then under Create database fill in the database name and press the create button.

**Comment by arozo** [comment]
what kind collision?

**Comment by arozo** [comment]
i ment collation

**Comment by arozo** [comment]
do i create table?

**Comment by DracoMilesX** [comment]
just leave default and no tables will get automatic created

**Comment by arozo** [comment]
ok what do i do now and sorry for wasting your time

**Comment by DracoMilesX** [comment]
start the script again/continue following the installation guide on the wiki considering your using Windows you need to figure out how to get google protobuf working first since that isn't added yet.

**Comment by arozo** [comment]
ok i will try my hardest

**Comment by arozo** [comment]
it says the same thing

**Comment by DracoMilesX** [comment]
Can you upload a screenshot of the error/phpmyadmin and ur mysql settings in ur cfg. Remove ur google information ofcourse

**Comment by arozo** [comment]
![help](https://cloud.githubusercontent.com/assets/21093662/18227197/85f99584-7270-11e6-9108-db337f6005ba.PNG)

**Comment by arozo** [comment]
![help](https://cloud.githubusercontent.com/assets/21093662/18227204/ad056da6-7270-11e6-90f5-a68beee6a96d.PNG)

**Comment by DracoMilesX** [comment]
I suggest you modify pokémongo to pokemongo and in the database as well don't think it supports the special character on the e.

**Comment by DracoMilesX** [comment]
and you named the database pogoserver instead of pokemongo either do above or replace the database name in the cfg to pogoserver.

**Comment by arozo** [comment]
the cfg.js?

**Comment by DracoMilesX** [comment]
yes

**Comment by arozo** [comment]
that all?

**Comment by DracoMilesX** [comment]
yes if your phpmyadmin database name matches ur cfg.js database name try running it again after adding ur google info again.

**Comment by arozo** [comment]
ok

**Comment by arozo** [comment]
![help](https://cloud.githubusercontent.com/assets/21093662/18227238/c2cb09ec-7271-11e6-8059-9098524ebe13.PNG)

**Comment by DracoMilesX** [comment]
What does the error above it says? Most likely you don't got protobuf installed. Try googling how to install google protobuf windows.

You will need to do some figuring out yourself here since it's the hardest part. Even I haven't figured it out yet.

**Comment by arozo** [comment]
oh it says no file cfg so i will rename it

**Comment by arozo** [comment]
same error from the start again

**Comment by arozo** [comment]
omg fixed it the data base is pokémongo instead of pokemongo

**Comment by arozo** [comment]
thank you so much

**Comment by icefyy** [comment]
please may you help me with MySQL workbench. i have the same error and i dont know what to do

**Comment by DracoMilesX** [comment]
https://github.com/maierfelix/POGOserver/wiki/Windows-Installation/97cf32d0084686f4949a1f8cdcd734f56e0a2714

**Comment by icefyy** [comment]
thankyou, although i cant do the command window part. it doesnt show up
