### ISSUE TITLE
"The Server has crashed!"

### ISSUE THREAD

**Issue by Nou4r** [maierfelix/POGOserver#15]
http://i.imgur.com/C0iwK8Z.png
Im using an external database..

**Using PTC not Google**

**Comment by shinsen26** [comment]
InGame, log into google account, this will fix your issue

**Comment by Nou4r** [comment]
It happens without me trying to login and play pokemon go on my phone...

**Comment by shinsen26** [comment]
Yes i know, but when you play on pokemon go, choose Google account, not PTC

**Comment by maierfelix** [comment]
Gets handled by f455867
