### ISSUE TITLE
constant loading loop?

### ISSUE THREAD

**Issue by acaruana2004** [maierfelix/POGOserver#155]
so i can start up the pokemon server and load into it, as normal, but when i open up the console i get a constant loop of the same scripts. this is such a pain because i can only write half a command without the game re-running the looping script, i will provide a picture

![pokemon server loop](https://cloud.githubusercontent.com/assets/21985321/18231101/b8c10cf0-72a6-11e6-80ac-e374c2de1914.PNG)

would be nice to know if there is a simple fix, thanks ;)

**Comment by maierfelix** [comment]
The game asks the server for map objects (pokestops, encounters etc.) all few seconds, so this is normal behaviour. To change the refresh interval, do edits [here](https://github.com/maierfelix/POGOserver/blob/master/src/modes/index.js#L17)

**Comment by acaruana2004** [comment]
unfortunately nothing changed, is there any other values affecting it?

> The game asks the server for map objects (pokestops, encounters etc.) all few seconds, so this is normal behaviour. To change the refresh interval, do edits here

**Comment by maierfelix** [comment]
Restart both client and server, if that doesnt fix it you are doing something else wrong. Make sure you use the pre-release under release tab
