### ISSUE TITLE
Lastest repository error

### ISSUE THREAD

**Issue by ranrinc** [maierfelix/POGOserver#170]
I  believe the current GIT cant be used at all. I encounter error 

<img width="576" alt="screen shot 2016-09-13 at 7 24 57 pm" src="https://cloud.githubusercontent.com/assets/15801696/18473596/f66af9b0-79e7-11e6-8042-450be77c1de9.png">

Will this be resolve soon? or we just need to be patient..

**Comment by Badley187** [comment]
start command = npm run boot

try this

**Comment by ranrinc** [comment]
@Badley187 it work.. thanks.. but now upon login the server say Invalid provider! Kicking..
Removed null

Any help? Furthermore API pages did not shown any Google Map. What did I do wrong?

**Comment by cliffsmits007** [comment]
@ranrinc  with wich account do you login? 

PTC or Google? cause PTC works fine for me

**Comment by ranrinc** [comment]
@cliffsmits007 Testing using my PTC account. Unsure why? Running Rooted Nexus 5X

**Comment by cliffsmits007** [comment]
@ranrinc  i tested with Nox on my pc i didnt rooted my phone yet.
the strange thing is i made a Guide for API and the map works for me.

[https://camo.githubusercontent.com/900568deaad33c81406a4631ecafb5f93d69e087/68747470733a2f2f696d616765732d322e646973636f72646170702e6e65742f2e654a77467751454b7779414d414d435f2d41426a6a64485a333467364b37534e6141614673625f763771732d383153374f6b54473267464b58356c6e30557434706c5a315932356e54614d766e666d434a4a4c796364566246746a4e577952796842473944527436734e5a464e42694e435f5179686f4b486433397130654e75367663487672596831772e6435456d53416574474b6b685f766a336c6e7167487168567759512e706e67](url)

**Comment by ranrinc** [comment]
@cliffsmits007 
![capture](https://cloud.githubusercontent.com/assets/15801696/18513301/2d2f66be-7ab7-11e6-84ec-cf62254d9e47.PNG)

Thats is the error messages and on my Android it say Unable to authenticate. Please try again

**Comment by cliffsmits007** [comment]
i had yesterday the same  Unable to authenticate on my pc.
but i didnt recieve the invailed provider.

**Comment by ranrinc** [comment]
Continue with problem... I'm not sure... Maybe someone can help me out.

Using banned account and it work. However still unable to do nothing. Including the API website
Any help appreciated.

![api](https://cloud.githubusercontent.com/assets/15801696/18513978/d8b607de-7ab9-11e6-808d-1351355cc1c0.PNG)
![error](https://cloud.githubusercontent.com/assets/15801696/18513979/d8bec5b8-7ab9-11e6-947d-52fe5911999a.PNG)

**Comment by ranrinc** [comment]
Also how to create pokestop and Gym? or Spawn...

**Comment by cliffsmits007** [comment]
@ranrinc you need to have the map and press double click and select what you want

**Comment by ranrinc** [comment]
@cliffsmits007 map show error....Anyway to know how to set it up?

**Comment by cliffsmits007** [comment]
https://github.com/maierfelix/POGOserver/wiki/How-to-setup-API--services-through-Google-Console

try it i made a guide for it and worked for me

**Comment by ranrinc** [comment]
@cliffsmits007 Thanks for everything.. my bad.. I forget that I need to setup api cfg files...
stupid me...

**Comment by cliffsmits007** [comment]
Glad it helps for you.

**Comment by ranrinc** [comment]
@cliffsmits007 sorry for my stupidness..wondering how do I make PokeStop sending out goods. and how do I make spawn work? I have not being able to make it work at all..

**Comment by undertakermad** [comment]
@ranrinc I'm having the "Invalid provider! Kicking.." error using a valid PTC account.
How do you solve it?
Thanks!
