### ISSUE TITLE
[master] Table 'pogosql.spawn_points' doesn't exist

### ISSUE THREAD

**Issue by MZorzy** [maierfelix/POGOserver#171]
git pull, last commit 5caf7c0
copied cfg.js.example to cf.js and edited login data
npm install
npm run boot

[Console] https://github.com/maierfelix/POGOServer
[Console] Booting Server v0.5.8
[Console] Downloaded assets are valid! Proceeding..
[Console] MySQL connection established
[Console] Server listening at -----
[Console] API access for localhost granted!
[Console] localhost logged in!
[Console] Error: ER_NO_SUCH_TABLE: Table 'pogosql.spawn_points' doesn't exist
[Console] Synced 515191-------- with database..
[Console] Error: ER_NO_SUCH_TABLE: Table 'pogosql.spawn_points' doesn't exist

**Comment by DracoMilesX** [comment]
try removing all tables in the pogosql database and re running it it might not create the new tables because you already have some of them.

**Comment by MZorzy** [comment]
OK
 i drop DB then recreate.
fixit thnx
