### ISSUE TITLE
Client unable to request models?

### ISSUE THREAD

**Issue by gFreezer** [maierfelix/POGOserver#172]
The client never sends a `/model` request to the server and also fails to load and display already downloaded models.
Does this mean that the `GET_ASSET_DIGEST` or `GET_DOWNLOAD_URLS` requests are broken somehow?

**Comment by maierfelix** [comment]
Did you tried entering your ip [here](https://github.com/maierfelix/POGOserver/blob/master/cfg.js.example#L23)?

**Comment by CineXWorm** [comment]
I have the same problem.
I entered my local and public ip
And both it doesnt solve the problem

**Comment by gFreezer** [comment]
I haven't. But I can't even find any reference to CFG.LOCAL_IP throughout the whole code...

**Comment by CineXWorm** [comment]
Weird,
I think dev will fix it.

**Comment by maierfelix** [comment]
Try replacing [this](https://github.com/maierfelix/POGOserver/blob/master/src/models/World/packets/GetDownloadUrls.js) file with [this](https://gist.github.com/maierfelix/6053458849d839f95a7b18abb8bd6c22)

**Comment by CineXWorm** [comment]
Thanks it works!
Can you explain us how items column structure is?
So i can give myself pokebals

**Comment by gFreezer** [comment]
Oh thanks, it works now if I enter my hostname instead of the IP.

The problem was that I entered my hostname in the Xposed module, so it didn't "recognize" the request with my IP address as a request to the custom server (I guess).

**Comment by gFreezer** [comment]
@CineXWorm Seems like querying the items from the database isn't implemented yet, but you can just change the values in [this file](https://github.com/maierfelix/POGOserver/blob/master/src/models/Player/Bag/index.js#L16) instead

**Comment by maierfelix** [comment]
Items are fetched from db, please stop mixing 2 issues

**Comment by gFreezer** [comment]
Well, this isn't really an issue anyway, just a mistake on my side, right? I'm closing it...
