### ISSUE TITLE
Error with babel

### ISSUE THREAD

**Issue by TrainZug** [maierfelix/POGOserver#173]
i get an error when typing npm run boot![dgggu2v](https://cloud.githubusercontent.com/assets/20605068/18478399/5e2c3800-79d1-11e6-9fab-fcff3ec89810.png)

**Comment by Cronick** [comment]
Try to run "npm install"

**Comment by TrainZug** [comment]
i tried but then this happens
![gyeh6ds - imgur](https://cloud.githubusercontent.com/assets/20605068/18488286/033958f6-79f9-11e6-9ad1-d11c990bd45f.png)

**Comment by DeadlyMelqn** [comment]
ive had this too but the descriptor.h is literally in my protobuf

**Comment by ranrinc** [comment]
Please follow my wiki regarding protobuf. The error cause by NO PROTOBUF.
