### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Themanwhoisit** [maierfelix/POGOserver#18]
Can't Start on my Debian Server:

`> POGOServer@0.2.5 start /root/pkmn/POGOserver-master
> nodemon --exec npm run babel-node -- ./src/index.js

npm ERR! POGOServer@0.2.5 start: `nodemon --exec npm run babel-node -- ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.2.5 start script.
npm ERR! This is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --exec npm run babel-node -- ./src/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! cwd /root/pkmn/POGOserver-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/pkmn/POGOserver-master/npm-debug.log
npm ERR! not ok code 0
`

And on Windows:
![image](https://cloud.githubusercontent.com/assets/20666474/17713481/7174c152-63fb-11e6-8078-27a648a69064.png)
![image](https://cloud.githubusercontent.com/assets/20666474/17713489/7d764f2a-63fb-11e6-9fd1-ee7800203caa.png)

**Comment by Cronick** [comment]
Try to run 'npm install'

**Comment by darksmartz** [comment]
npm install --save babel-preset-es2015

**Comment by Themanwhoisit** [comment]
On Debian the self ._. :

`./run-linux.sh

> POGOServer@0.2.5 start /root/pkmn/POGOserver-master
> nodemon --exec npm run babel-node -- ./src/index.js


npm ERR! POGOServer@0.2.5 start: `nodemon --exec npm run babel-node -- ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.2.5 start script.
npm ERR! This is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --exec npm run babel-node -- ./src/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! cwd /root/pkmn/POGOserver-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/pkmn/POGOserver-master/npm-debug.log
npm ERR! not ok code 0
`
The Log:

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@1.4.21
ss3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart POGOServer@0.2.5
6 info start POGOServer@0.2.5
7 verbose unsafe-perm in lifecycle true
8 info POGOServer@0.2.5 Failed to exec start script
9 error POGOServer@0.2.5 start: `nodemon --exec npm run babel-node -- ./src/ind$
9 error Exit status 1
10 error Failed at the POGOServer@0.2.5 start script.
10 error This is most likely a problem with the POGOServer package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     nodemon --exec npm run babel-node -- ./src/index.js
10 error You can get their info via:
10 error     npm owner ls POGOServer
10 error There is likely additional logging output above.
9 error Exit status 1
10 error Failed at the POGOServer@0.2.5 start script.
10 error This is most likely a problem with the POGOServer package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     nodemon --exec npm run babel-node -- ./src/index.js
10 error You can get their info via:
10 error     npm owner ls POGOServer
10 error There is likely additional logging output above.
11 error System Linux 3.16.0-4-amd64
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
13 error cwd /root/pkmn/POGOserver-master
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
`

**Comment by Themanwhoisit** [comment]
`/usr/bin/nodejs run start

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/pkmn/POGOserver-master/run'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
`

Can this help?

**Comment by Themanwhoisit** [comment]
I had a to old Node js version sorry
