### ISSUE TITLE
Command not work

### ISSUE THREAD

**Issue by felix-m-p** [maierfelix/POGOserver#183]
Why does the Command´s not work?
Warum funktionieren die Befehle nicht?

**Comment by Infinity1one** [comment]
in which version ? 0.4.9 commands are working in 0.5.X the commands arent working (spawn at least)

**Comment by Picki11** [comment]
ok Thanks my version was 0.5.x when the command`s works

**Comment by ranrinc** [comment]
@Picki11 try using API from localhost

**Comment by Picki11** [comment]
how can I open the api

**Comment by DracoMilesX** [comment]
Not all commands are implemented yet.

**Comment by Cronick** [comment]
As @DracoMilesX says. Not all commands has been implemented back after the 0.5.x update, as there was some structure changes.
