### ISSUE TITLE
Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by nicarmani** [maierfelix/POGOserver#191]
Excuse me, how i can fix this?

I successfully compiled protobuf but i can't figure what is wrong, i try with node v4 and v6 with the same results.

Win 10 64 bits

> 190 verbose linkBins node-protobuf@1.3.3
> 191 verbose linkMans node-protobuf@1.3.3
> 192 silly doSerial global-link 0
> 193 silly doParallel update-linked 0
> 194 silly doSerial install 1
> 195 silly install node-protobuf@1.3.3 C:\Users\Pablo\Desktop\Nueva carpeta (5)\POGOserver-master\node_modules\.staging\node-protobuf-16801450
> 196 info lifecycle node-protobuf@1.3.3~install: node-protobuf@1.3.3
> 197 verbose lifecycle node-protobuf@1.3.3~install: unsafe-perm in lifecycle true
> 198 verbose lifecycle node-protobuf@1.3.3~install: PATH: C:\Users\Pablo\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Pablo\Desktop\Nueva carpeta (5)\POGOserver-master\node_modules\node-protobuf\node_modules\.bin;C:\Users\Pablo\Desktop\Nueva carpeta (5)\POGOserver-master\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\adb;C:\Program Files\Java\jre7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\nodejs\;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\adb;C:\Program Files\Java\jre7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\nodejs\;C:\Users\Pablo\AppData\Local\Microsoft\WindowsApps;C:\Python27;C:\Python27\Scripts;C:\Users\Pablo\AppData\Roaming\npm
> 199 verbose lifecycle node-protobuf@1.3.3~install: CWD: C:\Users\Pablo\Desktop\Nueva carpeta (5)\POGOserver-master\node_modules\node-protobuf
> 200 silly lifecycle node-protobuf@1.3.3~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
> 201 silly lifecycle node-protobuf@1.3.3~install: Returned: code: 1  signal: null
> 202 info lifecycle node-protobuf@1.3.3~install: Failed to exec install script
> 203 verbose unlock done using C:\Users\Pablo\AppData\Roaming\npm-cache\_locks\staging-91bb3454566a2871.lock for C:\Users\Pablo\Desktop\Nueva carpeta (5)\POGOserver-master\node_modules\.staging
> 204 silly rollbackFailedOptional Starting
> 205 silly rollbackFailedOptional Finishing
> 206 silly runTopLevelLifecycles Finishing
> 207 silly install printInstalled
> 208 warn optional Skipping failed optional dependency /chokidar/fsevents:
> 209 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> 210 warn POGOServer@0.5.9 license should be a valid SPDX license expression
> 211 verbose stack Error: node-protobuf@1.3.3 install: `node-gyp rebuild`
> 211 verbose stack Exit status 1
> 211 verbose stack     at EventEmitter.<anonymous> (C:\Users\Pablo\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
> 211 verbose stack     at emitTwo (events.js:106:13)
> 211 verbose stack     at EventEmitter.emit (events.js:191:7)
> 211 verbose stack     at ChildProcess.<anonymous> (C:\Users\Pablo\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 211 verbose stack     at emitTwo (events.js:106:13)
> 211 verbose stack     at ChildProcess.emit (events.js:191:7)
> 211 verbose stack     at maybeClose (internal/child_process.js:877:16)
> 211 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 212 verbose pkgid node-protobuf@1.3.3
> 213 verbose cwd C:\Users\Pablo\Desktop\Nueva carpeta (5)\POGOserver-master
> 214 error Windows_NT 10.0.14393
> 215 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pablo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
> 216 error node v6.6.0
> 217 error npm  v3.10.7
> 218 error code ELIFECYCLE
> 219 error node-protobuf@1.3.3 install: `node-gyp rebuild`
> 219 error Exit status 1
> 220 error Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
> 220 error Make sure you have the latest version of node.js and npm installed.
> 220 error If you do, this is most likely a problem with the node-protobuf package,
> 220 error not with npm itself.
> 220 error Tell the author that this fails on your system:
> 220 error     node-gyp rebuild
> 220 error You can get information on how to open an issue for this project with:
> 220 error     npm bugs node-protobuf
> 220 error Or if that isn't available, you can get their info via:
> 220 error     npm owner ls node-protobuf
> 220 error There is likely additional logging output above.
> 221 verbose exit [ 1, true ]

**Comment by TheGarvinator** [comment]
What's the fix?
