### ISSUE TITLE
"node-gyp rebuild" fails. I have installed protobuf and put it into the PoGoServer folder.

### ISSUE THREAD

**Issue by TheGarvinator** [maierfelix/POGOserver#193]
I don't know why, but node-protobuf fails. Full log here: http://pastebin.com/bGqc5r1c
What the PoGo folder looks like: http://imgur.com/a/rtJi3

EDIT: I may have installed python wrong. I have had it a while, and I saw an error relating to that.

EDIT 2: Nope, python is installed right, and I recompiled protobuf just to make sure everything works.

EDIT 3: I found an edit that works, but it is not updated to the latest version of this git (e.g. no map.) If any of the creators want a link to the edit to help fix the bug, just ask.

**Comment by ranrinc** [comment]
@TheGarvinator follow my wiki regarding protobuf installation. After installation be sure to restart Windows. Then run the install-windows.bat Also be sure that protobuf directory also been copy to your pogoserver directory and add to protobuf path

**Comment by TheGarvinator** [comment]
I followed the wiki. I copied it to the folder. I don't know what you mean "add it to the protobuf path." Do you mean add it to the path in my environment variables?

**Comment by TheGarvinator** [comment]
Anyone have a working protobuf folder I could download?

**Comment by TheGarvinator** [comment]
This might help you guys fix the bug: http://imgur.com/a/itOyA

**Comment by ranrinc** [comment]
@TheGarvinator upon compilation of protobuf compile. You will have protobuf file on Install directory which you create earlier.  Copy install directory to your /POGOServer directory and rename it to protobuf. If this done correctly install-windows.bat will setup the correct path for protobuf and when you run that files you will have 4 yellow line which is confirm that protobuf done crorrectly. If you encounter red text message please restart windows and retry. Please let me know.

**Comment by TheGarvinator** [comment]
I restarted windows. Same error. I did exactly what the guide said. I copied over the instrall folder. I used the VS 2015 x64 command prompt. I used powershell for the start. Here is my full command prompt log. http://imgur.com/a/HBJra

**Comment by DeadlyMelqn** [comment]
Hello ranting,  perhaps providing a compiled photo but may help. I end up in some type of situation when I'm done compiling protobuf in Windows 10

**Comment by ranrinc** [comment]
@DeadlyMelqn unsure how you guys compile protobuf but if it done correctly as written then you should have protobuf ready to be used.

For running POGO server be sure to used command prompt and not powershell. My experience with powershell not working but it will run using command prompt.

**Comment by TheGarvinator** [comment]
I ran it with the command prompt. I followed the steps. I don't know why, but it just dont work.

**Comment by TheGarvinator** [comment]
Can someone send me a precompiled version?

**Comment by Tjchispas** [comment]
Try this node to me to run 
https://nodejs.org/dist/v4.5.0/node-v4.5.0-x64.msi

**Comment by TheGarvinator** [comment]
OK, now it cant find the module "Request"

**Comment by ranrinc** [comment]
@TheGarvinator POGO Server run only on the latest version for all the needed files. Using 4.5.0 Node will surely not allowing it to run.

**Comment by Tjchispas** [comment]
6.6.0 using node I always get this error  
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\xxxx\Desktop\Pokemon\POGOserver-master\node_modules\node-protobuf\build\protobuf.vcxproj]

**Comment by Abisai95** [comment]
I have the same error and i don't know because, I followed step by step the wiki and even so not working.

[http://imgur.com/a/sHp7n](http://imgur.com/a/sHp7n)

**Comment by Rendaman13** [comment]
Followed the wiki exactly to install protobuf. I copied the install directory into the pogo server folder and ran the install windows.bat. It's not working at all.

**Comment by TheGarvinator** [comment]
Using the latest version, I get the same error ad @Abisai95

**Comment by TheGarvinator** [comment]
Why close this? We were following instructions and got an error.

**Comment by DeadlyMelqn** [comment]
Agreed

**Comment by scorp12** [comment]
the idiot closing theeads is making rules up and closing things as he pleases. even if the thread is updates with info or new issues is no concern

**Comment by maierfelix** [comment]
@scorp12 This will no longer happen, however please mind your words

**Comment by Abisai95** [comment]
@TheGarvinator 
Solution.

1.Run npm -g install npm@next
2.Run Install-windows.bat
3.Run npm run boot or run-windows.bat

And finally work
