### ISSUE TITLE
wut is this?

### ISSUE THREAD

**Issue by phr34k0** [maierfelix/POGOserver#2]
Is this like a private server of some sort? Your git title is misleading.. MITM or Private server?

**Comment by ithr0n** [comment]
Yes, it is a re-implementation of the pokemon go server, based on the official available API.

You could call that a "private server".

**Comment by phr34k0** [comment]
Sweet so like it fetches character data from niantic or needs to create a new character data and stores it through its own db?

**Comment by maierfelix** [comment]
@phr34k0 Only various ingame models get retreived from the official servers. Everything else happens inside this version, as well as player data gets saved into database.

**Comment by phr34k0** [comment]
@maierfelix hence we need to recreate a new player account am i right? awechem! finally something worth playing instead of facing Niantic bans and flaws

**Comment by MZorzy** [comment]
There is a verbose mode to see/log what real app send out? Like deviceid to clone into bot ;-)
