### ISSUE TITLE
Nothing works, mind helping?

### ISSUE THREAD

**Issue by dayanfernandez** [maierfelix/POGOserver#200]
So i have been able to get it running on linux not windows. Buuuut no mayter what i do, the servers always crashes when attemping to login. Than the character logs in automatically,  even tho server crashed, but i still get stuck on TOS with the error unknow training mark request error.

Ive done everhthing, from reseting database, to putting local ip to cfg, to creating a user in database, to settting tutorial as complete in database. Nothing works, cant ever properly login.

No matter what user i make im database, client really never reads it, it always i believe trys to login to a random named "unknown" character.

Is this project still being developed?

**Comment by TheGarvinator** [comment]
So, first accept the tos without using the xposed module. Then activate the xposed module. By default, your username will be unknown on the server. Change that by doing /playername unknown NewName

**Comment by Cronick** [comment]
@TheGarvinator Please explain how you can change your playername with the /playername, cause that's not a command that has been implemented?

**Comment by TheGarvinator** [comment]
..? Umm... I'm using the version that they said to use in this discord: https://discordapp.com/channels/220682092139380758/221095603021676544 is this a whole different project..?
