### ISSUE TITLE
Can't see pokemon

### ISSUE THREAD

**Issue by innomeus** [maierfelix/POGOserver#202]
Hi, 

Everything in my server is running except for the pokemon visualization.

I can see the shadows at the radar and the circles in the ground, but i cannot see the pokemon.

I have read that I have to put my local IP at the cfg.js file, because is running in a virtual machine (lubuntu), i put my host ip at the line LOCAL_IP: "", but i don't know if that goes there or if i am introducing some data wrong.

For example, my virtual machine is 10.0.1.101 and my host is 10.0.1.5, is that ip (LOCAL_IP: "10.0.1.5") which  i have to put there?

Could be any other problem with any other thing? Everything except that is working on the server.

**Comment by demogorgonz** [comment]
Since you are using VM (Virtual Machine), you have to use local IP address of that VM.. so your answer is 10.0.1.101.

If you have tried to put local ip of host (10.0.1.5) you wouldn't get active (listening) service at all...

**Comment by innomeus** [comment]
But could that solve my problem? Is that i am trying to find out.

I will try that at home, then i will say someting about this.

**Comment by demogorgonz** [comment]
I have answered you from the aspect of networking... i do not run this server, i just observe progress and improvements :)

**Comment by innomeus** [comment]
I have the answer, i leave it blank that parameter and it works.
