### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by owency** [maierfelix/POGOserver#206]
Hello,

I came across this last night, and what a package! I was rather excited to catch some legendaries as you can imagine.
I managed to get everything (server side) working a treat, so i progressed on to the client side.
Here's where i've walked into many issues.
Long story short, it seems you now can't connect to POGO with a rooted android/xposed.
I havent yet had chance to try this with Nox, as I'm currently on a mac (Will try later this evening)
I've tried on a tablet, with the Xposed module, and using versions .35 and .37, yet i just get Unable to authenticate.
From research, it seems they're now using SafetyNet, which blocks xposed.

Can anyone else confirm this? Has anyone got around this? or am i just missing something?

Edit:

Ok so I've managed to get it to work with .35, however nothing spawns. Pokestops etc, and the pokeball in the top left just spins permanently?

**Comment by nliakm** [comment]
Nothing will spawn by default. You have to add pokestops and spawnpoints by yourself.

**Comment by Cronick** [comment]
Only 0.35 is supported for now.

**Comment by nogard230** [comment]
In cfg.js, try change game mode to 1.
Work for me, on .35.

**Comment by GabrielTK** [comment]
Sorry to ask, but what is the GameMode setting???

**Comment by Cronick** [comment]
GAME_MODE in cfg.js is not used for anything yet.
So what @nogard230 claims is false.

**Comment by owency** [comment]
This can be deleted, it was a dodge APK i downloaded. Found another version of .35 and its all working a treat. Thanks
