### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by brennoroxha** [maierfelix/POGOserver#207]
Error install, Windows 7

http://i.imgur.com/qJTd6cK.jpg

C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POGOserver-master>npm install
  && npm run start
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14

> POGOServer@0.4.9 start C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POGOs
erver-master
> nodemon --ignore tmp/ --ignore data/ --ignore logs/ --exec npm run babel-node
-- ./src/index.js

[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`

> POGOServer@0.4.9 babel-node C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\
POGOserver-master
> babel-node --presets=es2015 "./src/index.js"

C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POGOserver-master\node_modules
\bindings\bindings.js:83
        throw e
        ^

Error: %1 não é um aplicativo Win32 válido.
\\?\C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POGOserver-master\node_mod
ules\node-protobuf\build\Release\protobuf.node
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POGOserver-ma
ster\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POG
Oserver-master\node_modules\node-protobuf\protobuf.js:9:35)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\bnROCHA
\Desktop\Pacote_PokeServer(32BIT)\POGOserver-master\node_modules\babel-register\
lib\node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "babel-node" "./src/index.js"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.4.9 babel-node: `babel-node --presets=es2015 "./src/index.
js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.4.9 babel-node script 'babel-node --presets=
es2015 "./src/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets=es2015 "./src/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bnROCHA\Desktop\Pacote_PokeServer(32BIT)\POGOserver-master
\npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Cronick** [comment]
https://github.com/maierfelix/POGOserver/wiki/Windows-Protobuf-How-To
