### ISSUE TITLE
Docker problem: setting windows-path for db

### ISSUE THREAD

**Issue by nliakm** [maierfelix/POGOserver#210]
I installed and run my server with docker. everything works fine.
but i have a little problem, i cant solve.

For learning how to work with docker, i removed the mysql-server from the original dockerfile and created an other container only for the database. I also added, that the mysql database uses a data container, wich persistantly stores the databases files.

when i do it with linux, there is no problem (I choose the directory with the -v flag):
`docker run --name mysqldb --volumes-from mysql_data -v /var/lib/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=pogosql -p 3306:3306 mysql:latest`

When the server starts the first time, it writes the tables into the chosen directory.
but obviously with windows, I'm messing up with the syntax of the windows path.

i tried 
-v C:\\Pogoserver\\mysql
-v C:\Pogoserver\mysql
-v /c//Pogoserver/mysql
-v C:/Pogoserver/mysql

nothing worked. Any idea how to set the correct windows-path?

**Comment by DracoMilesX** [comment]
Try looking at #108 we where trying to get docker more proper with reduced storage and more in using it in more docker spirit like.

For windows it should be -v /var/lib/mysql:C\Pogoserver\mysql

**Comment by nliakm** [comment]
Thank you for the link. There are some useful tips to reduce the size of the containers!
i'll try it, when im at home.

I think why ':-v C:\Pogoserver\mysql:/var/lib/mysql' is not working because of the ':'. Its a key-sign and cant be used.

**Comment by DracoMilesX** [comment]
Might need another \ and / after mysql on both sides.

**Comment by nliakm** [comment]
Ok i fixed it.
My problem was, that i only used docker on linux machines. they have the permission to write and access files in the directories of the host-machine by default.
on windows, you have to manually add the allowed directories.

i did that and know it works fine!
