### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Lord-Haji** [maierfelix/POGOserver#211]
Can someone plz tell ? what does this signify ?
Rather what is this 
https://camo.githubusercontent.com/1e08129cdf1cfe6ab380f344cdfbe1c12abd4db1/687474703a2f2f692e696d6775722e636f6d2f483639325339642e706e67

**Comment by DracoMilesX** [comment]
It's the api branch it allows for webbased adding of gyms, pokestops and spawnpoints.

**Comment by Lord-Haji** [comment]
where's it avialable ?
coz node 6.5 isnt compatible with my Os

**Comment by DracoMilesX** [comment]
https://github.com/maierfelix/POGOserver/tree/api

What OS are you running? Considering Windows, Linux, Mac, Armv6/7/8 support node.

Place files in the root of your webfolder and then go to localhost/<folder>
