### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by dayanfernandez** [maierfelix/POGOserver#212]
So I downloaded the api branch , and added it into my xamp htdocs folder and edited the cfg to include the new api key.

Nothing happens , my site just continues to say CONNECTING , or CONNECTION FAILED , or LOGIN FAILED.

And the pic bellow Is of the console. What am I doing wrong ?
![untitled](https://cloud.githubusercontent.com/assets/7821084/18729494/0186262e-8020-11e6-8a09-13e512cec7ad.jpg)

**Comment by nogard230** [comment]
Are you add your pc host -> 192.168.48.1  localhost ?
Verify your apache permission and the server host on the file .save in POGO server directory.

**Comment by Cronick** [comment]
Use the latest version instead of v0.4.9

**Comment by dayanfernandez** [comment]
The latest version gives me issue's on running , something with protobuff error's. 4.9 is the one that I can get running for some reason

**Comment by Cronick** [comment]
Then you have the reason why. The API got improved in version v0.5, so update to get it to work.
