### ISSUE TITLE
help with installation

### ISSUE THREAD

**Issue by romeuwb** [maierfelix/POGOserver#214]
whenever I try to install the error below, can someone help me fix this?

![error](https://cloud.githubusercontent.com/assets/11163018/18738729/bff0e3ac-8074-11e6-91d3-8e33503f4ab1.JPG)

**Comment by DeadlyMelqn** [comment]
i have error this but descriptor.h is there.

**Comment by ranrinc** [comment]
Pls check WIKI guide on how to install protobuf on Windows.
