### ISSUE TITLE
node-gyp rebuild

### ISSUE THREAD

**Issue by Rendaman13** [maierfelix/POGOserver#237]
Running the batch file to install the server just gives me a bunch of error messages when it goes to node-gyp rebuild. I have the latest version of node.js, xammp, and this server.

**Comment by nliakm** [comment]
protobuf installed? Many people had the same problem before. Search through the issues, im sure you'll find the solution here.

**Comment by Rendaman13** [comment]
Ok, thanks. I'll see if I can compile a protobuf.
