### ISSUE TITLE
[Question] How to change your team?

### ISSUE THREAD

**Issue by Rendaman13** [maierfelix/POGOserver#240]
I was just wondering how to change your team once you get the server set up. Do you do it via the webapi or do you edit one of the .js scripts?

**Comment by Vankxr** [comment]
Database, i guess

**Comment by devilkkw** [comment]
just edit dbase "user" table, then use:
 0-no team
1-blue
2-red
3-yellow.


the sql command are:

UPDATE `pogo`.`users` SET `team`='2' WHERE `id`='88';

need to fix with your dbname,team selected and id of user.

**Comment by Rendaman13** [comment]
Thanks!
