### ISSUE TITLE
'node-gyp rebuild'.

### ISSUE THREAD

**Issue by scorp12** [maierfelix/POGOserver#242]
71 silly gunzTarPerm extractEntry nan_typedarray_contents.h
372 silly gunzTarPerm modified mode [ 'nan_typedarray_contents.h', 436, 438 ]
373 silly gunzTarPerm extractEntry nan_weak.h
374 silly gunzTarPerm modified mode [ 'nan_weak.h', 436, 438 ]
375 silly gunzTarPerm extractEntry tools/package.json
376 silly gunzTarPerm modified mode [ 'tools/package.json', 436, 438 ]
377 silly gunzTarPerm extractEntry tools/README.md
378 silly gunzTarPerm modified mode [ 'tools/README.md', 436, 438 ]
379 silly gunzTarPerm extractEntry tools/1to2.js
380 silly gunzTarPerm modified mode [ 'tools/1to2.js', 509, 511 ]
381 silly gentlyRm C:\Users\stinger\Desktop\PO\node_modules\.staging\node-protobuf-7781d8e9\node_modules is being purged
382 verbose gentlyRm don't care about contents; nuking C:\Users\stinger\Desktop\PO\node_modules\.staging\node-protobuf-7781d8e9\node_modules
383 silly gentlyRm C:\Users\stinger\Desktop\PO\node_modules\.staging\nan-6e4ecf98\node_modules is being purged
384 verbose gentlyRm don't care about contents; nuking C:\Users\stinger\Desktop\PO\node_modules\.staging\nan-6e4ecf98\node_modules
385 silly doParallel preinstall 3
386 silly preinstall bindings@1.2.1 C:\Users\stinger\Desktop\PO\node_modules\.staging\bindings-7ce2df79
387 info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
388 silly preinstall nan@2.4.0 C:\Users\stinger\Desktop\PO\node_modules\.staging\nan-6e4ecf98
389 info lifecycle nan@2.4.0~preinstall: nan@2.4.0
390 silly preinstall node-protobuf@1.3.3 C:\Users\stinger\Desktop\PO\node_modules\.staging\node-protobuf-7781d8e9
391 info lifecycle node-protobuf@1.3.3~preinstall: node-protobuf@1.3.3
392 silly lifecycle bindings@1.2.1~preinstall: no script for preinstall, continuing
393 silly lifecycle nan@2.4.0~preinstall: no script for preinstall, continuing
394 silly lifecycle node-protobuf@1.3.3~preinstall: no script for preinstall, continuing
395 silly doReverseSerial remove 0
396 silly doSerial move 0
397 silly doSerial finalize 3
398 silly finalize C:\Users\stinger\Desktop\PO\node_modules\bindings
399 silly finalize C:\Users\stinger\Desktop\PO\node_modules\nan
400 silly finalize C:\Users\stinger\Desktop\PO\node_modules\node-protobuf
401 silly doSerial build 3
402 silly build bindings@1.2.1
403 info linkStuff bindings@1.2.1
404 silly linkStuff bindings@1.2.1 has C:\Users\stinger\Desktop\PO\node_modules as its parent node_modules
405 verbose linkBins bindings@1.2.1
406 verbose linkMans bindings@1.2.1
407 silly build nan@2.4.0
408 info linkStuff nan@2.4.0
409 silly linkStuff nan@2.4.0 has C:\Users\stinger\Desktop\PO\node_modules as its parent node_modules
410 verbose linkBins nan@2.4.0
411 verbose linkMans nan@2.4.0
412 silly build node-protobuf@1.3.3
413 info linkStuff node-protobuf@1.3.3
414 silly linkStuff node-protobuf@1.3.3 has C:\Users\stinger\Desktop\PO\node_modules as its parent node_modules
415 verbose linkBins node-protobuf@1.3.3
416 verbose linkMans node-protobuf@1.3.3
417 silly doSerial global-link 0
418 silly doParallel update-linked 0
419 silly doSerial install 3
420 silly install bindings@1.2.1 C:\Users\stinger\Desktop\PO\node_modules\.staging\bindings-7ce2df79
421 info lifecycle bindings@1.2.1~install: bindings@1.2.1
422 silly lifecycle bindings@1.2.1~install: no script for install, continuing
423 silly install nan@2.4.0 C:\Users\stinger\Desktop\PO\node_modules\.staging\nan-6e4ecf98
424 info lifecycle nan@2.4.0~install: nan@2.4.0
425 silly lifecycle nan@2.4.0~install: no script for install, continuing
426 silly install node-protobuf@1.3.3 C:\Users\stinger\Desktop\PO\node_modules\.staging\node-protobuf-7781d8e9
427 info lifecycle node-protobuf@1.3.3~install: node-protobuf@1.3.3
428 verbose lifecycle node-protobuf@1.3.3~install: unsafe-perm in lifecycle true
429 verbose lifecycle node-protobuf@1.3.3~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\stinger\Desktop\PO\node_modules\node-protobuf\node_modules\.bin;C:\Users\stinger\Desktop\PO\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Users\stinger\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Users\stinger\AppData\Roaming\npm
430 verbose lifecycle node-protobuf@1.3.3~install: CWD: C:\Users\stinger\Desktop\PO\node_modules\node-protobuf
431 silly lifecycle node-protobuf@1.3.3~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
432 silly lifecycle node-protobuf@1.3.3~install: Returned: code: 1  signal: null
433 info lifecycle node-protobuf@1.3.3~install: Failed to exec install script
434 verbose unlock done using C:\Users\stinger\AppData\Roaming\npm-cache\_locks\staging-2be8311565027232.lock for C:\Users\stinger\Desktop\PO\node_modules\.staging
435 silly rollbackFailedOptional Starting
436 silly rollbackFailedOptional Finishing
437 silly runTopLevelLifecycles Starting
438 silly runTopLevelLifecycles Finishing
439 silly install printInstalled
440 warn optional Skipping failed optional dependency /chokidar/fsevents:
441 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
442 warn POGOServer@0.5.9 license should be a valid SPDX license expression
443 verbose stack Error: node-protobuf@1.3.3 install: `node-gyp rebuild`
443 verbose stack Exit status 1
443 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
443 verbose stack     at emitTwo (events.js:106:13)
443 verbose stack     at EventEmitter.emit (events.js:191:7)
443 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
443 verbose stack     at emitTwo (events.js:106:13)
443 verbose stack     at ChildProcess.emit (events.js:191:7)
443 verbose stack     at maybeClose (internal/child_process.js:877:16)
443 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
444 verbose pkgid node-protobuf@1.3.3
445 verbose cwd C:\Users\stinger\Desktop\PO
446 error Windows_NT 6.1.7601
447 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
448 error node v6.6.0
449 error npm  v3.10.3
450 error code ELIFECYCLE
451 error node-protobuf@1.3.3 install: `node-gyp rebuild`
451 error Exit status 1
452 error Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
452 error Make sure you have the latest version of node.js and npm installed.
452 error If you do, this is most likely a problem with the node-protobuf package,
452 error not with npm itself.
452 error Tell the author that this fails on your system:
452 error     node-gyp rebuild
452 error You can get information on how to open an issue for this project with:
452 error     npm bugs node-protobuf
452 error Or if that isn't available, you can get their info via:
452 error     npm owner ls node-protobuf
452 error There is likely additional logging output above.
453 verbose exit [ 1, true ]

**Comment by scorp12** [comment]
i have tried all solutions in the issue list, ived tried node 6.4 and 6.6, several protobuf attempts..

**Comment by Rendaman13** [comment]
Same. I've tried about everything, I'm beginning to think that this project doesn't work.

**Comment by scorp12** [comment]
im sure it works. seems many are having success. but it maybe something simply being overlooked or maybe a different version of something causing issues

**Comment by nliakm** [comment]
i also had problems with installing protobuf for windows. i recommend you to host the server on a linux machine or use docker.

**Comment by scorp12** [comment]
what does the docker do.

**Comment by scorp12** [comment]
what is it meant by create a container for the docker setup

**Comment by nliakm** [comment]
a container runs a piece of software. i set up my server with docker.
check my repo. all you have to do is (ofcourse you need docker installed) to configure the cfg.js and the docker-compose.yml.
than run the install.bat and the server will be up.

**Comment by scorp12** [comment]
ok thanx will check it out tonight after work

**Comment by scorp12** [comment]
downloading a docker toollkit for windows setup. will also try it on linux and see if i have any luck. will respond back afterwards

**Comment by Rendaman13** [comment]
I'm assuming this works on a virtual machine? I'm thinking about running Ubuntu on Virtualbox and see if it works there.

**Comment by nliakm** [comment]
you can install docker toolbox, which uses virtual box to run "boot2docker" on a virtual machine.
(b2d is a lightweight linux distribution based on tiny core linux) its way quicker than a whole linux os (like ubuntu) and uses less ressources.
or you can install the docker.msi which uses hyper-v.

**Comment by d0dUxDJ** [comment]
I personally tried for several, several hours to do this on Windows to no avail. I went past this point somehow (don't remember, sorry), but in the end I decided to just partition the drive and throw ubuntu in there. Best decision I've made recently. Couple of commands in the terminal and boom you're running. If you have any sort of knowledge about SQL you'll also set up the server way faster than I did, lol. Docker is a solution as well, but I found that a bit uneasy to use when I tried it. Good luck!

**Comment by Rendaman13** [comment]
Alright then. I'll use a linux virtual machine. Thank!

**Comment by GabrielTK** [comment]
Docker

**Comment by Rendaman13** [comment]
Is docker required or optional?

**Comment by d0dUxDJ** [comment]
If you opt to go for linux, optional.

**Comment by nliakm** [comment]
its optional. but the best option, if you just want to run the server and dont want to install a linux OS only for it.

**Comment by scorp12** [comment]
so far ive added an ubuntu vm. so far instructions are going good until i reached modifying the cfg file. permissions were locked to the files of pogoserver. i had to use gksudo nautilus to change the permissions of the folder and files in order to countiue installing npm instructions

**Comment by scorp12** [comment]
well i have ubuntu installed, and everything seemed like it worked well without errors until i get to npm install command. then i get the same error as i did on windows . node-gyp rebuild.

**Comment by scorp12** [comment]
why was this closed

**Comment by Cronick** [comment]
Protobuf related issues will get closed.
