### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by scorp12** [maierfelix/POGOserver#253]
so far good on vm setup. i now have an issue when running npm run boot. mysql client authenication not supported. ive search the web for help but all i can find is to upgrade. but im already at 5.7. ive check the config file on pogo and logins are correct aswell.

**Comment by DracoMilesX** [comment]
What is the exact error?

And have you created the database itself?

**Comment by scorp12** [comment]
it says
mysql error: ER_NOT_SUPPORTED_AUTH_MODE: client does not supporty the authentication protocal requested by server; consider upgrading mysql client

**Comment by DracoMilesX** [comment]
Try this:

http://stackoverflow.com/questions/2101694/mysql-how-to-set-root-password-to-null/36234358#36234358

**Comment by scorp12** [comment]
from what i can gather about it through forums and sites is mysql was installed but some tables, users and privliages were not installed correctly. it seems the mysql.cnf was not written in aswell. so removed and reinstalling the server again

**Comment by scorp12** [comment]
well im not sure whats going as of yet. but so far it appears using apt-get to install mysql server and client appears to be corrupting the files causing passwords to change. files missing. config files placed wrong. and services not to work right.   to top it up its next to impossible to remove mysql after this happens. havent determined yet if its ubuntu 16.04 or mysql 5.7 causing the issue. but will be testing more tomorrow on ubuntu 12 and 14 aswell as all three ubuntu server editions. if those are good ill try a different mysql version on ubuntu 16

**Comment by scorp12** [comment]
havent confirmed yet by trail. but ive come across an article stating ununtu isnt reliable with package installs or integrity of maintaining thoses files once installed. redhat,opensuse is the recommanded os for reliablity and intgrity of files. it seems ubuntu dies continous checks uodates and modifying  of files on a continous and unnoticed trend

**Comment by DracoMilesX** [comment]
Odd never heard of it myself and as well never had an issue with Ubuntu and have been using it for quiet some years now.

But you can try CentOS it's kinda like redhat but it's free.

**Comment by scorp12** [comment]
ok got everything solved, running server on linux os vm, xampp on host windows computer aswell as nox on windows. and everything seems to be connecting perfectly with no issues as of yet
