### ISSUE TITLE
Failed connection & cannot login Web Api

### ISSUE THREAD

**Issue by qnzboi102** [maierfelix/POGOserver#254]
I followed everything correctly in the wiki. Am i suppose to drop the whole folder or the files in it???

 little help with this please i dont understand everything is up and running.

after about 3 days i finally got to work and now the web API is killing me please help me anyone.

![fail api](https://cloud.githubusercontent.com/assets/21341121/19022385/9430f5b6-88a5-11e6-8d36-5216cab4c4e5.PNG)

**Comment by Cronick** [comment]
Have you allowed your web-api to connect to POGOserver?
If it's not allowed to connect, it should tell you in the console.

**Comment by qnzboi102** [comment]
i ran the command npm run api and its telling me that its at localhost:9000 but that refuses. I dont know what i did wrong i also added it to the trusted users still to no avail.

**Comment by qnzboi102** [comment]
see from the screen 


![console](https://cloud.githubusercontent.com/assets/21341121/19022430/c348d1f6-88a6-11e6-9f7c-a72f31cdc33c.PNG)

**Comment by DracoMilesX** [comment]
Once you run the pogoserver you get shown an ip with :3000 after it fill in that ip in your cfg for api_allowed_host

**Comment by qnzboi102** [comment]
gotcha let me try that real quick so dont run npm run api correct

**Comment by qnzboi102** [comment]
now i am getting the unknown request.

i dont understand y its using https:// shouldnt it be plain http:/?

**Comment by qnzboi102** [comment]
i fixed the issue instead of the ip address i used localhost/(MY_FOLDER_NAME) and it worked 

thanks for who help
