### ISSUE TITLE
up and running

### ISSUE THREAD

**Issue by scorp12** [maierfelix/POGOserver#262]
i finally got the server up and running with no issues as of yet.  my setup is a windows 7 host computer with linux vm.

server from on vm
xampp for api on host
nox player on host

everything seems to be connecting correctly

**Comment by Rendaman13** [comment]
Glad to see someone got it working. I still can't figure out what's wrong with install-windows.bat because I keep getting the node-gyp rebuild error.

**Comment by scorp12** [comment]
i had the same issue.  i installed a linux vm and got it running. once the hurricane pass through here and things are more stable im gonna work on setting it up windows and see if i can figure out.
