### ISSUE TITLE
Can't log in (DB Users?)

### ISSUE THREAD

**Issue by nisanb** [maierfelix/POGOserver#27]
Hi !
I'm having problems to connect

1. I installed Xposed but im not sure if it redirects my POGOServer or PKGO
2. I tried manually adding a user to the SQL DB, but I don't see a password field?

Thanks!

**Comment by KeJunMao** [comment]
1. POGOsever after the success of the start, will show the 127.0.0.1:3000, such as Nox, you only need to fill in your local area network IP pokemon-go-xposed.
For example 192.168.1.2:3000

2. The pass is your original password.

**Comment by TomCools** [comment]
When i try this, i get "As a security measure, your account has been disabled for 15 minutes...". I am using **Nox App Player** and i have installed Xposed framework and the Pokemon Certificate thing, however it looks like  i'm still being connected to the actual servers. Any idea what I might be missing (server is not being hit at all).

**Comment by guto00741** [comment]
have you tried to login with google account ?

**Comment by TomCools** [comment]
No, I tried with the PokemonComp account.
On Aug 17, 2016 8:40 PM, guto00741 <notifications@github.com> wrote:have you tried to login with google account ?

**Comment by guto00741** [comment]
when i try to login by pct i got the same error , but by google account it worked

**Comment by maierfelix** [comment]
Seems like not related to this project itself
