### ISSUE TITLE
STILL no fix for node-gyp rebuild on install-windows.bat

### ISSUE THREAD

**Issue by Rendaman13** [maierfelix/POGOserver#270]
I have followed the wiki EXACTLY. I have compiled protobuf, installed XAMPP and the latest version of node.js. I can't use Ubuntu because VirtualBox no longer works on my Windows after the update. Looking at other people's issues doesn't help because they keep getting closed before they get answered. Any solutions? I'm on Windows 10.

**Comment by Badley187** [comment]
it´s hard to compile protobuf on windows... try to install protobuf from the git source
https://github.com/google/protobuf

after you got protobuf to install, you need to check if its installed to your PATH.
after that your error is solved

**Comment by Rendaman13** [comment]
Installed protobuf and added to windows path. Error persists. Argh.

**Comment by Badley187** [comment]
try mnaual install without install-windows.bat
npm install node-protobuf && npm install
the bat file try to set your path...

**Comment by Rendaman13** [comment]
This time when I got the error, I read it completely. From what I understand, "gyp" doesn't support the version of "python.exe" which is v3.5.0. Do I need to update/downdate my python?

**Comment by Badley187** [comment]
install phyton 2.7

**Comment by Rendaman13** [comment]
Thank you.

**Comment by Rendaman13** [comment]
Reopening due to error. Now, it proceeds a little further in the installation, but then it displays a bunch of yellow text before giving me the same error. Here's a photo:
![err](https://cloud.githubusercontent.com/assets/22496266/19223158/b870b8d0-8e36-11e6-8058-82bc51a419a8.png)

**Comment by Cronick** [comment]
This is a "temporary" fix for those who can't compile node-protobuf.
https://mega.nz/#!4JMhVS5a!WniZ6K-l-sbP5YMgrO13n0WzspXiMZ7qAb7NEWZ79LU

Copy the node-protobuf folder from the zip into your node_modules folder.
(If there already is an node-protobuf folder, then delete it first)

After you have copied the folder into node_modules.
Try to run "npm install" again, and it should not result in errors with protobuf.

**Comment by Rendaman13** [comment]
npm install worked
install windows.bat only gave me warnings instead of errors.
However, npm run boot fails on all accounts.

**Comment by scorp12** [comment]
try running npm run start instead of npm run boot

**Comment by scorp12** [comment]
![2016-10-09 20_47_01-npm](https://cloud.githubusercontent.com/assets/6216835/19225083/9c13276a-8e61-11e6-95f0-e0a85ef08e6e.png)


finally got it running using @cronic temp fix folder suggestion. and using npm run start instead of npm run boot

**Comment by Rendaman13** [comment]
Glad it's working for you, no matter what I try, it still doesn't work.

**Comment by Cronick** [comment]
Would suggest that you update to latest version @scorp12, as I can see you are using v0.4.9, and we are currently at v0.6.0.

@Rendaman13 What error do you get by running "npm run boot"?

**Comment by scorp12** [comment]
working on updating now. thanks @cronick for seeing that

**Comment by Rendaman13** [comment]
@Cronick 
![annoying error](https://cloud.githubusercontent.com/assets/22496266/19225312/0650226c-8e68-11e6-8d82-1a0011b26f6c.jpg)

**Comment by Cronick** [comment]
@Rendaman13 You need to rename your cfg.js.example to cfg.js

**Comment by Rendaman13** [comment]
Argh. I knew I was missing something. Thanks.
