### ISSUE TITLE
Is it still possible to get the assets?

### ISSUE THREAD

**Issue by PenguinsFlyGood** [maierfelix/POGOserver#272]
Still possible to get game assets now that the api is broken? Want to make my own private server but don't feel like setting it up if its impossible.

**Comment by Vankxr** [comment]
I have them. Just a matter of uploading them.

**Comment by Badley187** [comment]
Its still possible.

**Comment by GabrielTK** [comment]
The API Changed Again???

**Comment by Badley187** [comment]
Yesterday i have setup the WattOs VM and have downloaded the assets. Its still possible !!!

**Comment by maierfelix** [comment]
@PenguinsFlyGood the server runs independant of the api, it only relies on [these](https://github.com/AeonLucid/POGOProtos) proto files

**Comment by PenguinsFlyGood** [comment]
@Vankxr could you pm those to me?

@maierfelix alright, so I just DL the protos and put them in the src directory?

**Comment by vankxr** [comment]
Sure @PenguinsFlyGood

Is there any way to PM on GitHub? I am kinda new here

**Comment by Cronick** [comment]
There is not a PM system on Github @Vankxr

**Comment by Lucashamburguru** [comment]
@Vankxr found the data in the wattos image, thanks though. weird github doesn't have a pm system.
