### ISSUE TITLE
Stuck at ToS

### ISSUE THREAD

**Issue by Albert62** [maierfelix/POGOserver#279]
Stuck at the ToS
-Latest commit.

**Comment by Albert62** [comment]
Figured out by creating it manually on MySQL. Thanks for nothing.

**Comment by Rendaman13** [comment]
How exactly did you fix this? I'm having the same problem and I manually set Mysql but the error persisted.

**Comment by Albert62** [comment]
@Rendaman13 It's actually very easy. Turn off the server, go to the users table in MySQL and create your account manually.
The value of tutorial must be `'{"0":1,"1":1,"3":1,"4":1,"7":1}'`.
The email must be the same exact one that you're trying to log into.
Here is an example:
`INSERT INTO users VALUES (1, 'Admin', 'youraccount@gmail.com', 20000000, 40, 10000, 1000, 2, 50, 143, 0, 0, 0, '{}', '{}', '{}', '{}', '{"0":1,"1":1,"3":1,"4":1,"7":1}');`
