### ISSUE TITLE
Question for root

### ISSUE THREAD

**Issue by MOBSTERX** [maierfelix/POGOserver#28]
How can i open the pokemon app if im rooted? Cause i have everything setup but it just crashes.

**Comment by MOBSTERX** [comment]
I think i may have found the issue by downloading nintendo bypasser with xposed.

**Comment by MOBSTERX** [comment]
Nope still crashes

**Comment by Pinoloko** [comment]
your server is running fine?

 for client side, download xposed framework, and this module : https://github.com/rastapasta/pokemon-go-xposed/releases

install framework and the module, then configure your server ip on the module

**Comment by MOBSTERX** [comment]
Yea server is up but cant get passed niantic labs logo

**Comment by Pinoloko** [comment]
are you playing on nox? case positive, go to the nox settings , advanced and set your render to directx, restart nox and try again.

**Comment by MOBSTERX** [comment]
Im on Android 4.4 on a regular phone.

**Comment by MOBSTERX** [comment]
im trying a different one just trying to get root access.

**Comment by nisanb** [comment]
hey i'm trying with nox, set everything up, rooted, and installed module and framework
but it seems like pkgo is still pointing to official servers

also, how do I configure a user on localhost? (I see the users table, insert a new record but it seems like there is no password field)

**Comment by Pinoloko** [comment]
Sorry  @MOBSTERX,  no ideias on how to solve it on a real phone. 

@nissanb 

Have you started the module on the xposed? Go to xposed framework>modules and then start the one you've installed.  Then reboot your phone and try again

About the SQL,  you want to create a user to play or a user on the DB?

**Comment by nisanb** [comment]
Thanks for commenting.
I was referring to creation of a user to play.

Also, I've already done the steps you mentioned about xposed 

Could you add me on Skype?
Nisan.univ

**Comment by nisanb** [comment]
I'm now getting "Our servers are humbled ..."

Xposed log:

**Comment by nisanb** [comment]
![image](https://cloud.githubusercontent.com/assets/20663443/17723372/480e0aac-6442-11e6-9dc0-5978b1d97817.png)

**Comment by MOBSTERX** [comment]
I got the framework working on 4.4 android. You need a special one. As for root i replace kingroot with superuser after many attempts since i can only root with kingroot. If anyone needs help and has the same problem as me let me know. I solved my problems. Except the server is acting up now.

**Comment by MOBSTERX** [comment]
@nisanb Go to cmd on your windows computer and when the command prompt comes up type in ipconfig where it says IPv4 Address it give give some random address like 192.168 or something like this you should be connecting to that instead of 127.0.0.1

**Comment by MOBSTERX** [comment]
Whoops clicked the close button sorry guys i reopened it tho

**Comment by nisanb** [comment]
Thanks!
It's now talking to the server, but server crashes as soon as I login
