### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by eugenio412** [maierfelix/POGOserver#299]
I see some quietness here, is there someone that could make it work? I would like to try but I will not waste my time trying if it's not working anymore! 

Btw seems to be a nice hack! 

Thank you all

**Comment by Furtif** [comment]
Soon, I hope everything is blocked in api 0.35.
But the server walks with Nox and 0.35 application, follow the steps in the readme file.

Greetings

**Comment by Cronick** [comment]
This is still working. POGOserver does not use the API for 0.35, so that has no effect on POGOserver.

**Comment by eugenio412** [comment]
Ok, Thank you, could it work on iPhone? or should I go with a simulated android?

**Comment by Cronick** [comment]
You can use both probably.
Have never tested on a iPhone.

**Comment by Furtif** [comment]
Iphone try this: https://tutuapp.com/index.php?r=TutuappGenuine/PokemonGo install TutuHelper then give access in Settings-> General> Profiles (or devices), and then select "verify application" tutuhelper launch the application you will find pokemon go install and make even procedure (Settings-> General > profiles (or devices) and authorize, before logging was selecting the places to avoid the ban.

Greetings

**Comment by Furtif** [comment]
PS: Install the application with rabbit icon;)

Greetings

**Comment by eugenio412** [comment]
Thank you a lot! 👍🏻
