### ISSUE TITLE
Add POGOProtos as submodule and do not just copy over the contents

### ISSUE THREAD

**Issue by ithr0n** [maierfelix/POGOserver#3]
Reference to the original POGOProtos by using submodule functionality of GIT, instead of copying the files into own repository.

So you can track and apply changes very easily.

https://github.com/AeonLucid/POGOProtos

**Comment by cyraxx** [comment]
Or go with [node-pogo-protos](https://github.com/cyraxx/node-pogo-protos) if you'd like to save another step 😃

**Comment by maierfelix** [comment]
@cyraxx Thank you :-)
