### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by must-classrecord** [maierfelix/POGOserver#30]
> POGOServer@0.2.7 start C:\Users\xtaticlight\Desktop\POGO\POGOserver
> nodemon --exec npm run babel-node -- ./src/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! POGOServer@0.2.7 start: `nodemon --exec npm run babel-node -- ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the POGOServer@0.2.7 start script 'nodemon --exec npm run babel-node -- ./src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the POGOServer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --exec npm run babel-node -- ./src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs POGOServer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls POGOServer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xtaticlight\Desktop\POGO\POGOserver\npm-debug.log

**Comment by maierfelix** [comment]
Seems like error not related to this project itself
