### ISSUE TITLE
Unable to start server on CentOS7

### ISSUE THREAD

**Issue by xomikronx** [maierfelix/POGOserver#31]
Unable to start server.  It's looking for **node_modules/babel-node/package.json** which doesn't exist.

`> POGOServer@0.2.7 start /var/www/MYDOMAIN/POGOserver
> nodemon --exec npm run babel-node -- ./src/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`
npm ERR! Error: ENOENT, open '/var/www/MYDOMAIN/POGOserver/node_modules/babel-node/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.28.2.el7.x86_64
npm ERR! command "node" "/bin/npm" "run" "babel-node" "./src/index.js"
npm ERR! cwd /var/www/MYDOMAIN/POGOserver
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/MYDOMAIN/POGOserver/node_modules/babel-node/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/MYDOMAIN/POGOserver/npm-debug.log
npm ERR! not ok code 0
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by maierfelix** [comment]
Seems like not a pogoserver related issue

**Comment by xomikronx** [comment]
@maierfelix any suggestions? 

So I am able to install node-babel, I'm not an expert, but I don't know if it's the same package just named differently because of distro.  I tried symlinking it to babel-node, which removes the error, but just hangs like this:

`> POGOServer@0.2.7 start /var/www/go.chutastic.com/POGOserver
> nodemon --exec npm run babel-node -- ./src/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run babel-node ./src/index.js`
[nodemon] clean exit - waiting for changes before restart`

**Comment by durankeeley** [comment]
Here is a step by step CentOS-7 Install guide

sudo yum update
sudo yum install epel-release
sudo yum install git nodejs npm

wget https://github.com/taaem/nodejs-linux-installer/releases/download/v0.3/node-install.sh
sudo sh node-install.sh
curl -L https://www.npmjs.com/install.sh | sudo sh

git clone https://github.com/maierfelix/POGOserver.git
cd POGOserver
sudo sh run-linux.sh



### 1st Install dependencies and update ###
### 2nd Update Node & npm ###
### 3rd Download & install POGOserver ###

**Comment by xomikronx** [comment]
Getting this during install:
`> nodegit@0.14.1 install /var/www/MYDOMAIN/POGOserver/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Running install script

/var/www/MYDOMAIN/POGOserver/node_modules/nodegit/lifecycleScripts/install.js:30
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at Module.install (/var/www/MYDOMAIN/POGOserver/node_modules/nodegit/lifecycleScripts/install.js:30:14)
    at Object.<anonymous> (/var/www/MYDOMAIN/POGOserver/node_modules/nodegit/lifecycleScripts/install.js:56:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3`

As well as this:
`npm ERR! Linux 3.10.0-327.28.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.14.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the nodegit@0.14.1 install script 'node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:`

**Comment by durankeeley** [comment]
@xomikronx you are right if you run the steps in sequence then it doesn't work, you would have to reboot for it to take. Updated the above to reflect this.
