### ISSUE TITLE
Unable to connect to POGO SERVER

### ISSUE THREAD

**Issue by MafioLive** [maierfelix/POGOserver#343]
im trying to connect to my pogo server and everytime it gets about halfway done the loading bar before it stops doing anything...
heres my console output

[Console] ##### 18:54:47
[Console] DOWNLOAD_REMOTE_CONFIG_VERSION 5 => 18
[Console] CHECK_CHALLENGE 9 => 3
[Console] GET_HATCHED_EGGS 9 => 2
[Console] GET_INVENTORY 9 => 38
[Console] CHECK_AWARDED_BADGES 9 => 2
[Console] DOWNLOAD_SETTINGS 9 => 187

then it stops logging and freeze
ik this repository is discontinued now but if any1 has any suggestions lmk.

**Comment by ZroIsHere** [comment]
Too many download settings, configure it again

**Comment by MafioLive** [comment]
@ZroIsHere I have been trying to figure out how to do this with absolutely no luck. do you know what file I have to change stuff in?

**Comment by bns34** [comment]
Looks like this doesn't work anymore...

**Comment by okidogi** [comment]
Same issue, 0.49 works though. Not sure if there's more game assets missing.

**Comment by MafioLive** [comment]
guys this thread was opened 3 years ago let it fucking die
