### ISSUE TITLE
[Feature Request] Download nessesary files

### ISSUE THREAD

**Issue by Nerdcoat** [maierfelix/POGOserver#36]
After I read that someone made this amazing thing, I dreamd about the time niantic shut down this game forever, but we can play it after all. 

For this, we need a packet with all files who are nessesary before the server are offline. 
Its a feature request, but I think important. Anyway, thousand thanks for your work!

**Comment by maierfelix** [comment]
Implemented by https://github.com/maierfelix/POGOserver/commit/3dc5e303ad103d270e8ff86d8767fc7da2acdc5f
