### ISSUE TITLE
MySQL Error: connect

### ISSUE THREAD

**Issue by ooseraphimoo** [maierfelix/POGOserver#43]
______ _____ _____ _____
            | ___ \  _  |  __ \  _  |
            | |_/ / | | | |  \/ | | | ___  ___ _ ____   _____ _ __
            |  __/| | | | | __| | | |/ __|/ _ \ '__\ \ / / _ \ '__|
            | |   \ \_/ / |_\ \ \_/ /\__ \  __/ |   \ V /  __/ |
            \_|    \___/ \____/\___/ |___/\___|_|    \_/ \___|_|

[Console] Booting Server v0.3.1...
[Console] Created asset download session
[Console] MySQL Error: connect ECONNREFUSED 127.0.0.1:3306
[Console] Retrying again in 0s
[Console] MySQL Error: connect ECONNREFUSED 127.0.0.1:3306

**Comment by shyim** [comment]
Have you local a MySQL server running?

**Comment by m3g4mInD** [comment]
Just install mysql server in machina open port and all goes fine .

**Comment by Badley187** [comment]
pls exlpain how to install the database correct. i have installed the MYSQL Server but i get 
 MySQL Error: ER_BAD_DB_ERROR: Unknown database 'pogosql'
thx :)

**Comment by gionata-bisciari** [comment]
I got it too, try to replace 'pogosql' with 'Mysql'  on cfg.js it worked for me
It should look like this:
```
export const SERVER_MYSQL_DB_NAME = "Mysql";
```
