### ISSUE TITLE
Can't see the roads on the map

### ISSUE THREAD

**Issue by TomCools** [maierfelix/POGOserver#45]
Hi,

I'm trying to connect to the server using Nox. I was wondering what kind of Google API key we need, since it's not explicitly listed on the page? I have tried all 4 types and none of them render the roads for me.

Kind regards,
Tom

**Comment by icdance** [comment]
it seems something related to Nox. the map shows on my device, but get nothing with Nox.

**Comment by TomCools** [comment]
Ok, thanks for that info. Do you see Pokestop Images in Nox? because that also doesn't show up. Just making sure if it's the server or Nox.

**Comment by icdance** [comment]
pokestop image won't show on my nox either. 2nd thing, Nox won't show pokemon if i spawn more than 2 pokemons, while on my android device it can show as many as i spawn.

**Comment by TomCools** [comment]
Ok, good to know, maybe we can add a list of known issues on Nox? Or would that be beyond the scope of your porject @maierfelix.

**Comment by maierfelix** [comment]
@TomCools Black pokestops are a known issue with nox. Right now, the roads only load, if they got cached earlier (like when you connect to the official servers). The gmap key in the config is the official used one.
@icdance i cant reproduce your last mentioned issue, everything is working fine for me.

**Comment by icdance** [comment]
seems i find the reason. it is the %{ip} get in js.
i will see if i can find the code

**Comment by rastapasta** [comment]
updated the xposed module - thanks to @fehnomenal
