### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by WesVleuten** [maierfelix/POGOserver#5]
I would love to see mysql being supported

**Comment by iiTehEpicGuy** [comment]
Yes, We need MySQL on this. I'm way better using MySQL than MongoDB.

**Comment by TachyonRSA** [comment]
First thing I was thinking as well when I saw this.

**Comment by maierfelix** [comment]
Working on it, should be finished by tomorrow

**Comment by strigona-worksight** [comment]
I would like to suggest looking into PostgreSQL, it has much better geo-spacial support which will be beneficial to a project like this.

**Comment by maierfelix** [comment]
Implemented mysql, automatically creates database table if not found. Should be in exact the same stage as mongodb is right now.

**Comment by WesVleuten** [comment]
Thank you!
