### ISSUE TITLE
error     node-gyp rebuild

### ISSUE THREAD

**Issue by Badley187** [maierfelix/POGOserver#53]
i got with the mega update this

60127 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
60128 error node v6.4.0
60129 error npm  v3.10.3
60130 error code ELIFECYCLE
60131 error node-protobuf@1.3.3 install: `node-gyp rebuild`
60131 error Exit status 1
60132 error Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
60132 error Make sure you have the latest version of node.js and npm installed.
60132 error If you do, this is most likely a problem with the node-protobuf package,
60132 error not with npm itself.
60132 error Tell the author that this fails on your system:
60132 error     node-gyp rebuild
60132 error You can get information on how to open an issue for this project with:
60132 error     npm bugs node-protobuf
60132 error Or if that isn't available, you can get their info via:
60132 error     npm owner ls node-protobuf
60132 error There is likely additional logging output above.
60133 verbose exit [ 1, true ]

i have the latest node and npm installed. any solution? sorry for my bad english^^

**Comment by maierfelix** [comment]
See the install instructions [here](https://www.npmjs.com/package/node-protobuf)

**Comment by Badley187** [comment]
its to hard to understand for me -.- i need protobuf i know but there are many versions... then i dont know how to include it... without the mega update the server was running... with this its to hard for me :/ but thx for your help and great work :)

**Comment by maierfelix** [comment]
If anyone got stuck on the compilation process of the proto files, try these: [protobuf.zip](https://mega.nz/#!JgkxDIBB!Az3W7mnk1ksDiPcqzDSU44Iv1Xxpw1lVWZTx7UV9RhA)

**Comment by Eagle351** [comment]
https://github.com/google/protobuf/blob/master/cmake/README.md I found this page very helpful when I compiled protobuf on windows7 64bit. The only problem I faced that was not in this guide was using the advice on here http://stackoverflow.com/questions/7865432/command-line-compile-using-cl-exe 
also when compiling I had to set the path to most of the stuff like CL.exe, Cmake and GIT 
I struggled but got there :-)

**Comment by Badley187** [comment]
big thx for your help :) i tried to set the enviroment... but i get the same error :/

**Comment by maierfelix** [comment]
@Badley187 Just saw the problem is related to node-gyp (*facepalm*). Which windows and which nodejs version do you have? Im not sure, but node-gyp should be included with the latest nodejs build.

**Comment by HusbandoMax** [comment]
I'm not having any luck so far either.

**Comment by Badley187** [comment]
i tried this installion guide but no luck :/  https://github.com/nodejs/node-gyp

**Comment by maierfelix** [comment]
Closed, since not related to this project iself
