### ISSUE TITLE
How do i solve this issue?

### ISSUE THREAD

**Issue by UknownAssassin** [maierfelix/POGOserver#54]
ive been told to install GIT but i know nothing about the application. Ever since i updated i cant run the server.
https://images-ext-2.discordapp.net/eyJ1cmwiOiJodHRwczovL3MxNC5wb3N0aW1nLm9yZy82MmxlazN1ZXAvVW50aXRsZWQucG5nIn0.phelnv8Nd2ic4m5pxH2NthQD1N0.png

**Comment by maierfelix** [comment]
Install [git](https://git-scm.com/downloads)
