### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by HusbandoMax** [maierfelix/POGOserver#56]
I installed the previous version fine about 15 hours ago and had it running now when I tried to install again I'm getting the c++ error which is weird seems I'd already instaalled now I'm getting.
https://puu.sh/qK0bL/b9cbd645ee.png
Also tried installing the version i'd already had running again but the same issue.

**Comment by maierfelix** [comment]
Already mentioned here: https://github.com/maierfelix/POGOserver/issues/53
