### ISSUE TITLE
No Pokestops and pokemons In new Version ?

### ISSUE THREAD

**Issue by srg84** [maierfelix/POGOserver#57]
Hi, I have installed new version, from 0, changed database from Mongo to Mysql, and now, no pokestops appear neither any pokemon.

Another thing, maybe it's a good idea a Linux manual, i'm getting crazy about all missing packets...

sudo apt-get install nodejs
sudo apt-get install npm
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
sudo apt-get install protobuf-compiler 
sudo apt-get install build-essential
sudo apt-get install mysql-server

Thanks for the good job!.

**Comment by maierfelix** [comment]
If console doesnt show any error and your gets cyan colored logs like below, everything should be fine on that side.
````
Got request: GET_MAP_OBJECTS
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
[Console] Sent pm0112 to `xx@gmail.com
````
Possibly you are at the wrong location, since last commit, i just throw a fresh GetMapObjects dump into the packets.

Try setting your gps location to: 
````
latitude: 39.1882905753091
longitude: -96.58363568771144
````

**Comment by srg84** [comment]
That's it, thank you!

It's normal, I can't catch Mew and pokestops rewards, doesn't save in bag?

**Comment by maierfelix** [comment]
Working on getting these things working, right now. However it will took some days, since i have to rework the whole packet thing as well as many database related things.
