### ISSUE TITLE
gmaps data from mobilemaps.clients.google.com

### ISSUE THREAD

**Issue by icdance** [maierfelix/POGOserver#58]
it seems something blocks it, which prevent route showing in game on Nox.

**Comment by Cronick** [comment]
It's not because something is blocking it.

The API key provided in the cfg is simply not activated, and would recommend that people is changing it to their own API key instead of using a public available one.

**Comment by icdance** [comment]
routes will show if traffic redirected with fiddler, which indicates api key is working, while routes won't show if use pogo xposed redirected to endpoint.

**Comment by Kidel** [comment]
that's strange. This morning it worked fine for me. Now it doesn't work anymore.

**Comment by Kidel** [comment]
basically after updating to commit 6f89cd13ab6d7662dd64fd10587eb1029f5107fb
from ed932ae48147d5bd865174d186e85c92f7cea838

But I don't think it's related. Maybe my client had the map in cache from connecting to the official server or something. I'm using my own working api key.

**Comment by Kidel** [comment]
Yes, I can confirm it. Logging to official server loads the map, then logging to PoGoServer shows it. If I delete my PokemonGo data and simply log to PoGoServer then the map is not loaded. 

The GMaps API works fine. Simply no requests from PoGoServer (and my public IP is also in allow list)

**Comment by Kidel** [comment]
Also (maybe it's related) spawn is not working
>/spawn tano.design CHARIZARD 22
[Console] Spawned 2x CHARIZARD's to tano.design at 41.7746016:12.4396275!
/spawn tano.design MEWTWO 234
[Console] Spawned 23x MEWTWO's to tano.design at 41.7743816:12.4400875!

But nothing on my client map.

**Comment by maierfelix** [comment]
Gmaps doesnt work, since it seems like the xposed module doesnt forward the gmap url correctly (slash missing?).
@Cronick already opened an issue here: https://github.com/rastapasta/pokemon-go-xposed/issues/12

**Comment by Kidel** [comment]
Nice.

**Comment by rastapasta** [comment]
updated the xposed moudle - thanks to @fehnomenal
