### ISSUE TITLE
Discord Channel

### ISSUE THREAD

**Issue by TachyonRSA** [maierfelix/POGOserver#6]
Create permanent link for Discord server instead of temporary one. It has already expired.

**Comment by iiTehEpicGuy** [comment]
Just tell the devs to make a infinite link.

**Comment by TachyonRSA** [comment]
Let me update the issue for that.

**Comment by maierfelix** [comment]
Updated discord link in https://github.com/maierfelix/POGOserver/commit/54473ef8d745571fef8b8368536a2fa1834efc31
Someone may want to manage?

**Comment by TachyonRSA** [comment]
`Updated discord link in 54473ef
Someone may want to manage?`

Will manage it if you want :)
