### ISSUE TITLE
Many errors and then the server shuts down

### ISSUE THREAD

**Issue by jcmillions** [maierfelix/POGOserver#60]
Here is the debug file

[npm-debug.txt](https://github.com/maierfelix/POGOserver/files/431409/npm-debug.txt)

**Comment by firebolt55439** [comment]
This looks like an npm install error. Try installing the dependencies manually (e.g. `npm install X` for each of them and figure out which fails).

**Comment by Badley187** [comment]
i have solved this with Oracle VM and ubuntu 16.04 LTS installed. its hard to get it to work on windows.

**Comment by firebolt55439** [comment]
No surprise there - even Cygwin's support for UNIX tools isn't fully-fleshed out. Ubuntu is an excellent choice.

**Comment by Badley187** [comment]
now i have some little issues

Got request: GET_PLAYER
Got request: CHECK_CHALLENGE
[Console] Dump traffic: Error: Invalid request type!
/save
[Console] /sav is not a valid command!
/savee
[Console] Saved 1 player into database!
/spawn Admin MEWTWO 50
[Console] Failed to spawn MEWTWO to player Admin!

1.) I got the Dump traffic error
2.) i need the command /savee to save a player. 
3.) the command spawn failed for me
4.) i only see pokestops and can spin them, but no pokemons spawn 
5.) I dont see any Gym

I use Oracle VM with Ubuntu 16.04 LTS and the server starts without an error.
maybe i missing some things?

**Comment by srg84** [comment]
My player has noname also and no pokestops appear neither any pokemon.
