### ISSUE TITLE
Error: File asset_digest was not found!

### ISSUE THREAD

**Issue by Kidel** [maierfelix/POGOserver#66]
Installed, then it downloaded Pokémon assets, then 
[Console] Error: File asset_digest was not found!

Restarted

[Console] Booting Server v0.4.2...
[Console] Error: File asset_digest was not found!

**Comment by Cronick** [comment]
The latest version is v0.4.3. The latest update should fix this problem.

**Comment by Kidel** [comment]
Thanks. I downloaded it early today and I didn't notice there was a new versione already.

**Comment by Kidel** [comment]
Worked. Now I have to understand why Pokémon go doesn't connect to the private server.
The network seems fine. I go to my ip:port from my phone browser using 3g and I get 
>Unknown request url: https://xxxxx:3002/
But even using  PokemonGoXposed the client still logs to the official server

**Comment by Kidel** [comment]
Ok, worked correctly. However after the server says

>Got request: GET_MAP_OBJECTS
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS

The client can only see my character with no pokemon around and no stops on the map. Also infinite spinning pokeball in the upper corner. How do I add Pokémon and stops?
