### ISSUE TITLE
Not writing on mysql

### ISSUE THREAD

**Issue by Kidel** [maierfelix/POGOserver#67]
As shown here:
http://imgur.com/a/WehWt

Using an existing pokemon go user. 

Also there is no pokemon or map data on the client, at least in my surroundings. 
I'm using my own google maps key

**Comment by ruchern** [comment]
Know issue. I am facing the problem too.

**Comment by Kidel** [comment]
Ok, I'll be waiting then. Thanks

**Comment by Kidel** [comment]
Any workaround for now?

**Comment by icdance** [comment]
a. you may insert a row manually. it works
b. map will show if you use fiddler to redirect traffic see
c. pokemons will show by using spawn command

**Comment by Kidel** [comment]
a. ok, I'll do it, thanks
b. ?
c. any command I type is not a valid command however.

**Comment by Kidel** [comment]
Added data manually. Pretty random looking now, but if I try to do something like changing trainer looks, the game crashes and, of course, rows on mysql are not edited.

**Comment by Badley187** [comment]
how add i the data manually?

**Comment by ruchern** [comment]
@icdance Well, the data will be reset after you logout.

**Comment by ruchern** [comment]
@Badley187 Install Phpmyadmin on your Ubuntu server.

**Comment by icdance** [comment]
@ruchen exp/lat/lng and other stuff like avatars can save:)

**Comment by Kidel** [comment]
Odd. Latitute and Longitude are written correctly in my database. I had 0,0 before, and now there are my real coordinates.

**Comment by Badley187** [comment]
i have solved this by my self :) but spawn isnt working for me... the server crashed

**Comment by Kidel** [comment]
Spawn not working here either. Not crashing however, I even get the green text, but no Pokémon shows up. Probably because of Xposed gmaps bug?

Also I tried to make a Mewtwo from database. Funny how CP is 0, but the problem is that the pic in inventory is fine, but the 3d model never shows up when I open the Pokémon page. Is that normal?

**Comment by maierfelix** [comment]
I forward everyone here to go further on [discord](https://discord.gg/gu8ZUJp), since the github issues arent suitable for such discussions.
