### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by rca17** [maierfelix/POGOserver#70]
Hello everyone I have this error I don't know what to do

0 info it worked if it ends with ok
1 verbose cli [ '/home/usr/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/home/usr/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'babel-node',
1 verbose cli   './src/index.js' ]
2 info using npm@3.10.6
3 info using node@v6.4.0
4 verbose run-script [ 'prebabel-node', 'babel-node', 'postbabel-node' ]
5 info lifecycle pogoserver@0.4.3~prebabel-node: pogoserver@0.4.3
6 silly lifecycle pogoserver@0.4.3~prebabel-node: no script for prebabel-node, continuing
7 info lifecycle pogoserver@0.4.3~babel-node: pogoserver@0.4.3
8 verbose lifecycle pogoserver@0.4.3~babel-node: unsafe-perm in lifecycle true
9 verbose lifecycle pogoserver@0.4.3~babel-node: PATH: /home/usr/.nvm/versions/node/v6.4.0/lib/node_modules/npm/bin/node-gyp-bin:/home/usr/POGOserver/node_modules/.bin:/home/usr/.nvm/versions/node/v6.4.0/lib/node_modules/npm/bin/node-gyp-bin:/home/usr/POGOserver/node_modules/.bin:/home/usr/.nvm/versions/node/v6.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle pogoserver@0.4.3~babel-node: CWD: /home/usr/POGOserver
11 silly lifecycle pogoserver@0.4.3~babel-node: Args: [ '-c', 'babel-node --presets=es2015 "./src/index.js"' ]
12 info lifecycle pogoserver@0.4.3~babel-node: Failed to exec babel-node script
13 verbose stack Error: pogoserver@0.4.3 babel-node: `babel-node --presets=es2015 "./src/index.js"`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/home/usr/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:852:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid pogoserver@0.4.3
15 verbose cwd /home/usr/POGOserver
16 error Linux 4.2.0-42-generic
17 error argv "/home/usr/.nvm/versions/node/v6.4.0/bin/node" "/home/usr/.nvm/versions/node/v6.4.0/bin/npm" "run" "babel-node" "./src/index.js"
18 error node v6.4.0
19 error npm  v3.10.6
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error pogoserver@0.4.3 babel-node: `babel-node --presets=es2015 "./src/index.js"`
24 error spawn ENOENT
25 error Failed at the pogoserver@0.4.3 babel-node script 'babel-node --presets=es2015 "./src/index.js"'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the pogoserver package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     babel-node --presets=es2015 "./src/index.js"
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs pogoserver
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls pogoserver
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by ruchern** [comment]
>25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the pogoserver package,

Make sure npm is latest.

Run `npm install` then `npm start`.

**Comment by Sygix** [comment]
Use this file : http://i.sygix.tk/POGOserver0.4.3.rar

**Comment by rca17** [comment]
That not help me
