### ISSUE TITLE
Not a valid command

### ISSUE THREAD

**Issue by Kidel** [maierfelix/POGOserver#71]
Am I doing something wrong?

>/save
[Console] /sav is not a valid command!
/clients
[Console] /client is not a valid command!
client
[Console] clien is not a valid command!
+client
[Console] +clien is not a valid command!
-client
[Console] -clien is not a valid command!
clientX
[Console] client is not a valid command!
update
[Console] updat is not a valid command!

**Comment by Badley187** [comment]
i have the same.... but use /savee or /clientss ;) then its work.

**Comment by Kidel** [comment]
yeah, it works like that.

**Comment by ruchern** [comment]
How do you all even type in command?

**Comment by Kidel** [comment]
in the Terminal. 
typing
/clients
produces 
[Console] client is not a valid command!
typing
/clientss
works fine
Basically 1 character gets cropped.

**Comment by Kidel** [comment]
Also I get the green text for spawn command, but no Pokémon shows up at my location. Is that because of the gmaps Xposed bug? 

And 3d model of a Mewtwo I added directly in database doesn't load. Pic in inventory is fine however, just 0 CP (I probably messed up with the multiplier)

**Comment by maierfelix** [comment]
Everything is working for me, you probably made something wrong. Please join [this](https://discord.gg/gu8ZUJp) discord channel to get further help.
