### ISSUE TITLE
New error after client update [Console] Dump traffic: Error: Invalid request type!

### ISSUE THREAD

**Issue by Kidel** [maierfelix/POGOserver#72]
>Got request: GET_DOWNLOAD_URLS
Got request: CHECK_CHALLENGE
Got request: GET_HATCHED_EGGS
Got request: GET_INVENTORY
Got request: CHECK_AWARDED_BADGES
Got request: DOWNLOAD_SETTINGS
[Console] Dump traffic: Error: Invalid request type!

**Comment by maierfelix** [comment]
This is ok, the used lib to decode the traffic is redundant and outdated. Will be fixed in next commit
