### ISSUE TITLE
Enhancement: public IP option in config

### ISSUE THREAD

**Issue by Kidel** [maierfelix/POGOserver#73]
I had many issues that Icd helped me solve on Discord. The problem appartently was the fact that I access my remote PoGo server using a public ip. 
It worked after I changed ${ip} in 
https://github.com/maierfelix/POGOserver/blob/master/src/packets/Responses.GetDownloadUrls.js
to my public ip.

If possible I'd suggest to add this option in config. People who'd like to run a private Pokémon GO server will also have those issues (like 3d models not being downloaded).

**Comment by icdance** [comment]
will be implemented in the next commit:)

**Comment by maierfelix** [comment]
Fixed in https://github.com/maierfelix/POGOserver/commit/3dc5e303ad103d270e8ff86d8767fc7da2acdc5f
