### ISSUE TITLE
Creating table undefined Problem

### ISSUE THREAD

**Issue by srg84** [maierfelix/POGOserver#74]
Deleted database pogosql and creating new one, installed from 0,

[Console] Booting Server v0.4.7...
[Console] Downloaded assets are valid! Proceeding..
[Console] Creating table **undefined**
       
This takes forever

**Comment by maierfelix** [comment]
Check the mysql details inside your cfg

**Comment by srg84** [comment]
MYSQL_TABLE: "users",

**Comment by maierfelix** [comment]
Download the cfg.js again and fill in your details, you propably corrupted some things
