### ISSUE TITLE
data I have in db is ignored in 0.4.7

### ISSUE THREAD

**Issue by Kidel** [maierfelix/POGOserver#75]
The bot worked fine in 0.4.5, then I updated to 0.4.7, redownloaded assets and restarted the bot.

I actually have no error messages, but everytime I log in the server says

>#####
Got request: GET_PLAYER
Got request: CHECK_CHALLENGE
[Console] xxx connected!
#####
Got request: GET_PLAYER
Got request: CHECK_CHALLENGE
[Console] xxx authenticated via Google!
[Console] xxx registered!

Even if the user 'xxx@gmail.com' is already in the database.

And of course the player has no Pokémon, no items and is level 1, while the one in the database has a bunch of things.

**Comment by srg84** [comment]
Me too, tables are empty

**Comment by Kidel** [comment]
I don't have empty tables, that was a known issues. I have manually added users and data that worked just fine before the last update.

**Comment by Kidel** [comment]
before the update: http://imgur.com/K0M7b3x
after the update: http://imgur.com/EN3c8Js

**Comment by ruchern** [comment]
Can confirm the same problem here.

**Comment by Kidel** [comment]
Also a small OT on something that is not clear. 
new cfg.js asks for LOCAL_IP, but I had to manually add my PUBLIC IP before in src/packets/Responses.GetDownloadUrls.js instead of ${ip}
So why do I have to specify my LOCAL ip in cfg.js now? For now I added my public ip there, because the server was already using my LAN ip.
However src/packets/Responses.GetDownloadUrls.js still uses ${ip}

**Comment by maierfelix** [comment]
Got the bug, its caused by when the player's party is empty. Also the current owned_pokemon table is missing the cp field

**Comment by TheDDoSFriend** [comment]
I still cant spawn pokemon and i dont have a username after the new update. I already added my username to the db

**Comment by srg84** [comment]
I have the same problem.

Someone has an SQL to fill pokemons table?

**Comment by Kidel** [comment]
So maierfelix, how do solve it? What do we have to add to the database? 
I have an old db filled with data from 0.4.5, what do I lack?

**Comment by Kidel** [comment]
So @maierfelix  how do solve it? What do we have to add to the database? 
I have an old db filled with data from 0.4.5, what does it need?

I have to delete the cp column, ok, but how do I get a player party?

@srg84 I do but it's useless at the moment, it's ignored.

**Comment by Kidel** [comment]
Solved by deleting "@gmail.com" from email in database
