### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by newjanson** [maierfelix/POGOserver#78]
It would be cool if people would be able to run this in docker.

**Comment by Kidel** [comment]
It's a node.js app, so I'm pretty sure you can do that already

**Comment by newjanson** [comment]
Ok, im going to rephrase it. It would be cool if a dockerfile would be included in the repo

**Comment by DracoMilesX** [comment]
#90 
Just waiting for it to get accepted.

**Comment by ruchern** [comment]
@DracoMilesX #90 won't be merged as there are conflicts at the moment. You have to fix them first.

**Comment by DracoMilesX** [comment]
@ruchern Yeah I saw it was because of the new merge from the dev branch will create a new PR.
