### ISSUE TITLE
Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by RecklessIt** [maierfelix/POGOserver#79]
Here's the log.
`60317 verbose cwd C:\Users\Marco\Desktop\Pokèmon GO\Server
60318 error Windows_NT 10.0.14393
60319 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
60320 error node v6.4.0
60321 error npm  v3.10.3
60322 error code ELIFECYCLE
60323 error node-protobuf@1.3.3 install: `node-gyp rebuild`
60323 error Exit status 1
60324 error Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
60324 error Make sure you have the latest version of node.js and npm installed.
60324 error If you do, this is most likely a problem with the node-protobuf package,
60324 error not with npm itself.
60324 error Tell the author that this fails on your system:
60324 error     node-gyp rebuild
60324 error You can get information on how to open an issue for this project with:
60324 error     npm bugs node-protobuf
60324 error Or if that isn't available, you can get their info via:
60324 error     npm owner ls node-protobuf
60324 error There is likely additional logging output above.
60325 verbose exit [ 1, true ]`

**Comment by Kidel** [comment]
That's probbly because you don't have protobuf or your env variables are not correct. See https://github.com/google/protobuf/blob/master/src/README.md

**Comment by RecklessIt** [comment]
I've set it up like:
Variable name: Path
Variable value: C:\protoc-3.0.0-win32\bin
Still not working..

**Comment by ruchern** [comment]
Try pulling the dev branch.

**Comment by alonoe** [comment]
@ruchern for me its working fine doing those steps, but cloning dev branch directly gave me erros about write permissions and npm

**Comment by ruchern** [comment]
@alonoe i don't understand why you have permission problems. Are you on Windows, Mac or Linux? Run i sudo for Mac/Linux

**Comment by RecklessIt** [comment]
git pull --all
git checkout dev
Can't do that unless I specify a repo

**Comment by MZorzy** [comment]
#94
