### ISSUE TITLE
Easier setup: Xposed module for API endpoint exchange

### ISSUE THREAD

**Issue by rastapasta** [maierfelix/POGOserver#8]
Heya @maierfelix,

nice project! To make the whole thing much more easier, I coded [pokemon-go-endpoint-xposed](https://github.com/rastapasta/pokemon-go-xposed) ;)

It makes it very easy to use your server without having to go through all the MITM setup, by simply replacing the URL of the API by hooking into the Android app's request method.

Enjoy and happy developing 😄 

![screenshot](https://i.imgur.com/NxGvrcy.png)

**Comment by rastapasta** [comment]
+ when using this, you won't need pokemon-go-xposed anymore for ssl pinning removal

**Comment by maierfelix** [comment]
This really makes things easier  :clap:

**Comment by KeJunMao** [comment]
good work！

**Comment by rastapasta** [comment]
* updated apk to newest version, better handling of configuration

**Comment by rastapasta** [comment]
actually going to merge this into pokemon-go-xposed. just makes so much more sense. keeping you updated.

**Comment by rastapasta** [comment]
done - this is part of pokemon-go-xposed now.  enjoy 😄
