### ISSUE TITLE
Field 'id' doesn't have a default value #####

### ISSUE THREAD

**Issue by srg84** [maierfelix/POGOserver#80]
Installed from 0, deleted and recreated database pogosql.

[Console] Error: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
#####

**Comment by maierfelix** [comment]
Fixed by https://github.com/maierfelix/POGOserver/commit/a500b0c6e1a5e55236ed6e025989bbd66ca8119d
Drop database and restart the server

**Comment by srg84** [comment]
Now, this error appears

[Console] Booting Server v0.4.9...
[Console] Downloaded assets are valid! Proceeding..
[Console] Creating table users
[Console] Creating table owned_pkmn
[Console] MySQL connection established
[Console] Server running at 192.168.0.22:3000

[Console] Error: ER_NO_DEFAULT_FOR_FIELD: Field 'item_poke_ball' doesn't have a default value
