### ISSUE TITLE
Field 'item_poke_ball' doesn't have a default value

### ISSUE THREAD

**Issue by srg84** [maierfelix/POGOserver#81]
Another database field problematic:

**[Console] Error: ER_NO_DEFAULT_FOR_FIELD: Field 'item_poke_ball' doesn't have a default value**

**Comment by Kidel** [comment]
run this sql query in your db:
>SET GLOBAL sql_mode='';

**Comment by srg84** [comment]
Fixed, Now works, except the playername says **unknown**.

-In the database the email field writes without **@gmail.com** and username = unknown.
- Master balls saves ok
- user table saves.
- personalize ok.
- no pokemon spawns at

latitude: 39.1882905753091
longitude: -96.58363568771144

spawn command doesn't exist.

**spawn
[Console] spaw is not a valid command!
spawnn
[Console] spawn is not a valid command!**

**Comment by Badley187** [comment]
to spawn u need this
/spawn username pokemonname amount
example
/spawn Admin mewtwo 20

**Comment by srg84** [comment]
/spawn Admin MEWTWO 50
[Console] Failed to spawn MEWTWO to player Admin!
/spawn Unknown MEWTWO 1       
[Console] Failed to spawn MEWTWO to player Unknown!
/spawn unknown MEW 1
[Console] Failed to spawn MEW to player unknown!

**Comment by srg84** [comment]
Ok, you have to stop/start server to load changes in dbs, then execute command:

/spawn unknown mew 1
[Console] Spawned 1x mew's to unknown at 39.1918334:-96.5831265!

But no pokemon appears
