### ISSUE TITLE
Error POGOServer

### ISSUE THREAD

**Issue by isoasd** [maierfelix/POGOserver#9]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart POGOServer@0.2.1
6 info start POGOServer@0.2.1
7 verbose unsafe-perm in lifecycle true
8 info POGOServer@0.2.1 Failed to exec start script
9 verbose stack Error: POGOServer@0.2.1 start: `nodemon --exec npm run babel-node -- ./src/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid POGOServer@0.2.1
11 verbose cwd C:\Users\IsoASD\Desktop\POGOserver-master
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error POGOServer@0.2.1 start: `nodemon --exec npm run babel-node -- ./src/index.js`
17 error Exit status 1
18 error Failed at the POGOServer@0.2.1 start script 'nodemon --exec npm run babel-node -- ./src/index.js'.
18 error This is most likely a problem with the POGOServer package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     nodemon --exec npm run babel-node -- ./src/index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs POGOServer
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls POGOServer
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by willyt1200** [comment]
Same exact issue. Tried both version of node/npm

**Comment by MOBSTERX** [comment]
Install https://nodejs.org click the current button install it. Put all files in c:\pgoserver\ You can rename it but its what i choose. Then run cd c:\pgoserver\ npm install in command prompt. That should get you one step closer.

**Comment by guto00741** [comment]
Try to run the following commands in npm 
npm install babel-cli -g
npm install nodemon -g

**Comment by ruchern** [comment]
Run

`npm install`

then 

`npm run`
