### ISSUE TITLE
npm not recognized

### ISSUE THREAD

**Issue by shadowangelo** [maierfelix/POGOserver#91]
npm install   && npm run start

'npm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Presario\Desktop\pogo\POGOserver-master>pause
Press any key to continue . . .

**Comment by ruchern** [comment]
Seriously a quick google search for 'npm' is not recognized.... can net you your solution.

Here's the spoodfed answer: https://www.npmjs.com/package/npm

**Comment by MZorzy** [comment]
really needed an installer of all packaged needed to start the server.

**Comment by shadowangelo** [comment]
i already figured it out. having another error atm
