### ISSUE TITLE
npm-debug.log <Please Help>   

### ISSUE THREAD

**Issue by Austinaries10** [maierfelix/POGOserver#98]
After I downloaded the file, i extracted it and run the .bat file. It came out this error. How to solve?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Acer-PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.7
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle POGOServer@0.5.0~prestart: POGOServer@0.5.0
6 silly lifecycle POGOServer@0.5.0~prestart: no script for prestart, continuing
7 info lifecycle POGOServer@0.5.0~start: POGOServer@0.5.0
8 verbose lifecycle POGOServer@0.5.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle POGOServer@0.5.0~start: PATH: C:\Users\Acer-PC\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Acer-PC\Desktop\personal\bot\POGOserver-master\POGOserver-master\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Acer\abFiles\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\CMake\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Acer-PC\AppData\Roaming\npm
10 verbose lifecycle POGOServer@0.5.0~start: CWD: C:\Users\Acer-PC\Desktop\personal\bot\POGOserver-master\POGOserver-master
11 silly lifecycle POGOServer@0.5.0~start: Args: [ '/d /s /c', 'npm run babel-node -- ./src/index.js' ]
12 silly lifecycle POGOServer@0.5.0~start: Returned: code: 1  signal: null
13 info lifecycle POGOServer@0.5.0~start: Failed to exec start script
14 verbose stack Error: POGOServer@0.5.0 start: `npm run babel-node -- ./src/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Acer-PC\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Acer-PC\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid POGOServer@0.5.0
16 verbose cwd C:\Users\Acer-PC\Desktop\personal\bot\POGOserver-master\POGOserver-master
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Acer-PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.5.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error POGOServer@0.5.0 start: `npm run babel-node -- ./src/index.js`
22 error Exit status 1
23 error Failed at the POGOServer@0.5.0 start script 'npm run babel-node -- ./src/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the POGOServer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run babel-node -- ./src/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs POGOServer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls POGOServer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sangokay** [comment]
i have the problem too
